# Generated by Django 5.2.6 on 2026-01-18 18:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('fornecedor', models.CharField(blank=True, max_length=50)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('custo_operacional', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('icms', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ipi', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pis_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('preco_sugerido', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('preco_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_entrada', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('is_servico', models.BooleanField(default=False, verbose_name='É um serviço')),
            ],
        ),
    ]
