# Generated by Django 5.2.6 on 2026-02-20 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_despesarecorrente_regracomissaotecnico_and_more'),
        ('estoque', '0002_produto_ponto_operacional_alter_produto_is_servico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='estoque.pontooperacional'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='estoque.pontooperacional'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ponto_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.pontooperacional'),
        ),
        migrations.CreateModel(
            name='VendaRapidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funcionario_numero', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pre_reserva', 'Pre-reserva'), ('vendida', 'Vendida'), ('cancelada', 'Cancelada')], default='pre_reserva', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixa.pagamento')),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_rapidas', to='estoque.pontooperacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_rapidas', to='estoque.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
