# Generated by Django 5.2.6 on 2026-02-20 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_pontooperacional_alter_movimentacaoestoque_destino_and_more'),
        ('orcamentos', '0001_initial'),
        ('ordens', '0004_ordemservico_codigo_portal_notificacaocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=14, unique=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('nome_contato', models.CharField(max_length=120)),
                ('telefone_contato', models.CharField(blank=True, max_length=30)),
                ('valido_ate', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('convertida', 'Convertida'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_estoque', to='orcamentos.itemorcamento')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_estoque', to='ordens.ordemservico')),
                ('ponto_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='estoque.pontooperacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='estoque.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoquePonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.pontooperacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_por_ponto', to='estoque.produto')),
            ],
            options={
                'ordering': ['ponto_operacional__codigo'],
                'unique_together': {('produto', 'ponto_operacional')},
            },
        ),
    ]
