# Generated by Django 5.2.6 on 2026-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_reservaestoque_saldoestoqueponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='destino_ubicacao',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
