# Generated by Django 5.2.6 on 2026-02-20 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_movimentacaoestoque_destino_ubicacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservaestoque',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaestoque',
            name='convertida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaestoque',
            name='expirada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaestoque',
            name='motivo_status',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('avaria', 'Avaria'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('reserva', 'Reserva'), ('consumo_os', 'Consumo em OS'), ('devolucao_reserva', 'Devolucao de reserva'), ('inventario', 'Inventario')], default='transferencia', max_length=20),
        ),
        migrations.CreateModel(
            name='InventarioEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='estoque.pontooperacional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventarioEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.IntegerField(default=0)),
                ('quantidade_contada', models.IntegerField(default=0)),
                ('ajuste', models.IntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventarioestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='estoque.produto')),
            ],
            options={
                'ordering': ['produto__nome'],
                'unique_together': {('inventario', 'produto')},
            },
        ),
    ]
