# Generated by Django 5.2.6 on 2026-02-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produto_estoque_minimo_reservaestoque_cancelada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendarapidaestoque',
            name='cesto_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='vendarapidaestoque',
            name='guia_pagamento',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
