# Generated by Django 5.2.6 on 2026-02-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_vendarapidaestoque_cesto_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacoes', to='estoque.pontooperacional')),
            ],
            options={
                'ordering': ['ponto_operacional__codigo', 'codigo'],
                'unique_together': {('ponto_operacional', 'codigo')},
            },
        ),
    ]
