# Generated by Django 5.2.6 on 2026-02-28 15:52

import django.core.validators
from django.db import migrations, models


def sincronizar_tipo_item(apps, schema_editor):
    Produto = apps.get_model("estoque", "Produto")
    Produto.objects.filter(is_servico=True).update(tipo_item="servico")
    Produto.objects.filter(is_servico=False).update(tipo_item="produto")


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_ubicacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_manual',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='taxa_cartao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_item',
            field=models.CharField(choices=[('produto', 'Produto'), ('servico', 'Servico')], default='produto', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='usar_aliquota_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(sincronizar_tipo_item, migrations.RunPython.noop),
    ]
