# Generated by Django 5.2.6 on 2026-03-06 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0025_fornecedorgarantia_cep_fornecedorgarantia_endereco'),
        ('estoque', '0009_produto_aliquota_manual_produto_cofins_produto_pis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('margem_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='valor_unitario_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_marketplace',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_estoque', to='configuracoes.fornecedorgarantia'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor_manual',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estoque/produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='garantia_peca_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_estoque', to='configuracoes.marcagarantia'),
        ),
        migrations.AddField(
            model_name='produto',
            name='margem_minima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.99)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='modelos_compativeis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='modo_preco',
            field=models.CharField(choices=[('simples', 'Simples'), ('avancado', 'Avancado')], default='avancado', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='observacao_interna',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='permite_os',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_minimo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada de estoque'), ('transferencia', 'Transferencia'), ('avaria', 'Avaria'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('reserva', 'Reserva'), ('consumo_os', 'Consumo em OS'), ('devolucao_reserva', 'Devolucao de reserva'), ('inventario', 'Inventario')], default='transferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_item',
            field=models.CharField(choices=[('produto', 'Produto'), ('peca', 'Peca'), ('consumivel', 'Consumivel'), ('servico', 'Servico')], default='produto', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoriaproduto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='servicos_compativeis',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='estoque.servicoreferencia'),
        ),
    ]
