# Generated by Django 5.2.6 on 2026-03-06 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_categoriaproduto_servicoreferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='bonus_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='percentual_comissao_peca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='permite_comissao_peca',
            field=models.BooleanField(default=False),
        ),
    ]
