# Generated by Django 5.2.6 on 2026-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_produto_bonus_venda_produto_percentual_comissao_peca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada de estoque'), ('transferencia', 'Transferência'), ('avaria', 'Avaria'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('reserva', 'Reserva'), ('consumo_os', 'Consumo em OS'), ('devolucao_reserva', 'Devolução de reserva'), ('inventario', 'Inventário')], default='transferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='is_servico',
            field=models.BooleanField(default=False, verbose_name='É um serviço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modo_preco',
            field=models.CharField(choices=[('simples', 'Simples'), ('avancado', 'Avançado')], default='avancado', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_item',
            field=models.CharField(choices=[('produto', 'Produto'), ('peca', 'Peça'), ('consumivel', 'Consumível'), ('servico', 'Serviço')], default='produto', max_length=20),
        ),
    ]
