# Generated by Django 5.2.6 on 2026-03-15 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_alter_movimentacaoestoque_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('margem_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoEquivalente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=160)),
                ('equivalente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalente_de', to='estoque.produto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalentes_principais', to='estoque.produto')),
            ],
            options={
                'ordering': ['produto__nome', 'equivalente__nome'],
                'unique_together': {('produto', 'equivalente')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_em_kits', to='estoque.produto')),
                ('produto_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_componentes', to='estoque.produto')),
            ],
            options={
                'ordering': ['produto_kit__nome', 'componente__nome'],
                'unique_together': {('produto_kit', 'componente')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoPrecoTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_tabela', to='estoque.produto')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_preco', to='estoque.tabelapreco')),
            ],
            options={
                'ordering': ['tabela__nome'],
                'unique_together': {('produto', 'tabela')},
            },
        ),
    ]
