# Generated by Django 5.2.6 on 2026-03-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_tabelapreco_produtoequivalente_produtokititem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_item',
            field=models.CharField(choices=[('produto', 'Produto'), ('peca', 'Peça'), ('consumivel', 'Consumível'), ('servico', 'Servico')], default='produto', max_length=20),
        ),
    ]
