# Generated by Django 5.2.6 on 2026-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_produto_custo_cac_produtohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='competencia_rateio',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_rateio_fixo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='incluir_rateio_custo_fixo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='previsao_venda_mensal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
