# Generated by Django 5.2.6 on 2026-03-20 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_produto_competencia_rateio_produto_custo_rateio_fixo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRateioCustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio_rateio', models.CharField(choices=[('unidades', 'Unidades previstas'), ('faturamento', 'Faturamento previsto'), ('margem', 'Margem prevista')], default='unidades', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao de rateio de custo fixo',
                'verbose_name_plural': 'Configuracoes de rateio de custo fixo',
            },
        ),
        migrations.CreateModel(
            name='RateioCustoFixoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(unique=True)),
                ('criterio_rateio', models.CharField(choices=[('unidades', 'Unidades previstas'), ('faturamento', 'Faturamento previsto'), ('margem', 'Margem prevista')], default='unidades', max_length=20)),
                ('total_custos_fixos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_base_rateio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_produtos', models.PositiveIntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-competencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RateioCustoFixoItemCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=120)),
                ('previsao_venda_mensal', models.PositiveIntegerField(default=0)),
                ('base_rateio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('participacao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('custo_rateio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_rateio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preco_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lucro_unitario_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_competencia', to='estoque.produto')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.rateiocustofixocompetencia')),
            ],
            options={
                'ordering': ['-custo_rateio_total', 'produto_nome'],
            },
        ),
    ]
