# Generated by Django 5.2.6 on 2026-03-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_configuracaorateiocustofixo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiocustofixoitemcompetencia',
            name='faturamento_realizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rateiocustofixoitemcompetencia',
            name='margem_realizada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rateiocustofixoitemcompetencia',
            name='quantidade_realizada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
