# Generated by Django 5.2.6 on 2026-05-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_estoqueevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada de estoque'), ('transferencia', 'Transferencia'), ('avaria', 'Avaria'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('reserva', 'Reserva'), ('consumo_os', 'Consumo em OS'), ('devolucao_reserva', 'Devolucao de reserva'), ('inventario', 'Inventario')], default='transferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='is_servico',
            field=models.BooleanField(default=False, verbose_name='E um servico'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modo_preco',
            field=models.CharField(choices=[('simples', 'Simples'), ('avancado', 'Avancado')], default='avancado', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_item',
            field=models.CharField(choices=[('produto', 'Produto'), ('peca', 'Peca'), ('consumivel', 'Consumivel'), ('servico', 'Servico')], default='produto', max_length=20),
        ),
        migrations.AlterField(
            model_name='produtohistorico',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criacao'), ('EDICAO', 'Edicao'), ('DUPLICACAO', 'Duplicacao'), ('IMPORTACAO', 'Importacao')], max_length=20),
        ),
    ]
