# Generated by Django 5.2.6 on 2026-06-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_inventarioestoque_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ubicacao_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_padrao', to='estoque.ubicacaoestoque'),
        ),
    ]
