# Generated by Django 5.2.6 on 2026-06-26 17:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_produto_ubicacao_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='destino_ubicacao_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='estoque.ubicacaoestoque'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='origem_ubicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='estoque.ubicacaoestoque'),
        ),
        migrations.AddField(
            model_name='reservaestoque',
            name='ubicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='estoque.ubicacaoestoque'),
        ),
        migrations.CreateModel(
            name='EstoqueCamadaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_entrada', models.PositiveIntegerField(default=0)),
                ('quantidade_saldo', models.PositiveIntegerField(default=0)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimento_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camadas_geradas', to='estoque.movimentacaoestoque')),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camadas_custo', to='estoque.pontooperacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camadas_custo', to='estoque.produto')),
                ('ubicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camadas_custo', to='estoque.ubicacaoestoque')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
                'indexes': [models.Index(fields=['produto', 'criado_em'], name='idx_camada_prod_criada'), models.Index(fields=['ponto_operacional', 'criado_em'], name='idx_camada_ponto_criada')],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoqueUbicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_ubicacao', to='estoque.pontooperacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_por_ubicacao', to='estoque.produto')),
                ('ubicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_produto', to='estoque.ubicacaoestoque')),
            ],
            options={
                'ordering': ['ponto_operacional__codigo', 'ubicacao__codigo', 'produto__nome'],
                'unique_together': {('produto', 'ubicacao')},
            },
        ),
    ]
