# Generated by Django 5.2.6 on 2026-07-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_inventarioestoque_ubicacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioestoque',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='estoque.categoriaproduto'),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='tipo_escopo',
            field=models.CharField(choices=[('ponto', 'Ponto operacional'), ('ubicacao', 'Ubicação')], default='ponto', max_length=20),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='conferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_inventario_conferidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='ean_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='margem_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='modelos_compativeis_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='motivo_divergencia',
            field=models.CharField(blank=True, choices=[('', 'Sem motivo'), ('falta', 'Falta'), ('sobra', 'Sobra'), ('local_errado', 'Item em local errado'), ('sem_etiqueta', 'Sem etiqueta'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='nome_snapshot',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='pmp_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='ponto_operacional_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='pvp_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('conferido', 'Confere'), ('divergencia', 'Divergência')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='ubicacao_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='inventarioestoque',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_conferencia', 'Em conferência'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
