# Generated by Django 5.2.6 on 2026-07-09 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0063_configuracaosistema_enviar_whatsapp_abertura_os_and_more'),
        ('estoque', '0027_inventarioestoque_categoria_inventarioestoque_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('fornecedor_manual', models.CharField(blank=True, max_length=120)),
                ('documento_numero', models.CharField(blank=True, max_length=40)),
                ('serie_documento', models.CharField(blank=True, max_length=20)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_entrada', models.DateField(default=django.utils.timezone.localdate)),
                ('frete_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('seguro_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('outras_despesas_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('desconto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacao', models.CharField(blank=True, max_length=220)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_mercadoria', to='configuracoes.empresa')),
                ('fornecedor_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_mercadoria', to='configuracoes.fornecedorgarantia')),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_mercadoria', to='estoque.pontooperacional')),
                ('ubicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_mercadoria', to='estoque.ubicacaoestoque')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntradaMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('impostos_entrada_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('frete_rateado_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('outras_despesas_rateadas_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('desconto_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacao', models.CharField(blank=True, max_length=160)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.entradamercadoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_entrada_mercadoria', to='estoque.produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='entradamercadoria',
            index=models.Index(fields=['status', '-criado_em'], name='idx_entmerc_status_criado'),
        ),
        migrations.AddIndex(
            model_name='entradamercadoria',
            index=models.Index(fields=['empresa', '-criado_em'], name='idx_entmerc_empresa_criado'),
        ),
        migrations.AddIndex(
            model_name='entradamercadoria',
            index=models.Index(fields=['ponto_operacional', 'status'], name='idx_entmerc_ponto_status'),
        ),
    ]
