# Generated by Django 5.2.6 on 2026-07-09 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0063_configuracaosistema_enviar_whatsapp_abertura_os_and_more'),
        ('estoque', '0028_entradamercadoria_itementradamercadoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_manual', models.CharField(blank=True, max_length=120)),
                ('codigo_fornecedor', models.CharField(blank=True, max_length=60)),
                ('custo_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prazo_medio_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('preferencial', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_relacionados_estoque', to='configuracoes.fornecedorgarantia')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_relacionados', to='estoque.produto')),
            ],
            options={
                'ordering': ['-preferencial', 'fornecedor_manual', 'id'],
            },
        ),
    ]
