# Generated by Django 5.2.6 on 2026-07-09 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_produtofornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioestoque',
            name='exige_aprovacao_divergencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='modo_contagem_cega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='divergencia_aprovada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminventarioestoque',
            name='divergencia_aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_inventario_aprovados', to=settings.AUTH_USER_MODEL),
        ),
    ]
