# Generated by Django 5.2.6 on 2026-07-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0030_inventarioestoque_exige_aprovacao_divergencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventarioestoque",
            name="exige_dupla_conferencia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iteminventarioestoque",
            name="quantidade_recontada",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iteminventarioestoque",
            name="recontado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iteminventarioestoque",
            name="recontado_por",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="itens_inventario_recontados", to=settings.AUTH_USER_MODEL),
        ),
    ]
