# Generated by Django 5.2.6 on 2026-07-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0031_inventarioestoque_exige_dupla_conferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementradamercadoria',
            name='lote_codigo',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='itementradamercadoria',
            name='lote_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itementradamercadoria',
            name='numeros_serie',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='controla_lote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='controla_serie',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EstoqueLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('validade', models.DateField(blank=True, null=True)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entrada_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_gerados', to='estoque.itementradamercadoria')),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_estoque', to='estoque.pontooperacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_estoque', to='estoque.produto')),
                ('ubicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_estoque', to='estoque.ubicacaoestoque')),
            ],
            options={
                'ordering': ['validade', 'criado_em', 'id'],
                'indexes': [models.Index(fields=['produto', 'quantidade_disponivel'], name='idx_lote_prod_saldo'), models.Index(fields=['validade'], name='idx_lote_validade')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'codigo', 'ponto_operacional', 'ubicacao'), name='uniq_lote_prod_ponto_ubic')],
            },
        ),
        migrations.CreateModel(
            name='EstoqueSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('baixada', 'Baixada'), ('avaria', 'Avaria')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entrada_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_geradas', to='estoque.itementradamercadoria')),
                ('movimento_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_baixadas', to='estoque.movimentacaoestoque')),
                ('ponto_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_estoque', to='estoque.pontooperacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_estoque', to='estoque.produto')),
                ('ubicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_estoque', to='estoque.ubicacaoestoque')),
            ],
            options={
                'ordering': ['produto__nome', 'numero'],
                'indexes': [models.Index(fields=['produto', 'status'], name='idx_serie_prod_status'), models.Index(fields=['numero'], name='idx_serie_numero')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'numero'), name='uniq_serie_prod_numero')],
            },
        ),
    ]
