# Generated by Django 5.2.6 on 2026-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_atendimentoposvendabalcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada de estoque'), ('transferencia', 'Transferencia'), ('avaria', 'Avaria'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('oferta', 'Oferta / brinde'), ('cedencia', 'Cedencia interna'), ('reserva', 'Reserva'), ('consumo_os', 'Consumo em OS'), ('devolucao_reserva', 'Devolucao de reserva'), ('inventario', 'Inventario')], default='transferencia', max_length=20),
        ),
    ]
