# Generated by Django 5.2.6 on 2026-08-02 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_empresa_rateio(apps, schema_editor):
    Empresa = apps.get_model("configuracoes", "Empresa")
    Configuracao = apps.get_model("estoque", "ConfiguracaoRateioCustoFixo")
    Snapshot = apps.get_model("estoque", "RateioCustoFixoCompetencia")
    empresa_unica = Empresa.objects.order_by("id").first() if Empresa.objects.count() == 1 else None
    if empresa_unica:
        Configuracao.objects.filter(empresa__isnull=True).update(empresa=empresa_unica)
        Snapshot.objects.filter(empresa__isnull=True).update(empresa=empresa_unica)
        return
    for snapshot in Snapshot.objects.filter(empresa__isnull=True):
        empresas = list(
            snapshot.itens.exclude(produto__empresa__isnull=True)
            .values_list("produto__empresa_id", flat=True)
            .distinct()[:2]
        )
        if len(empresas) == 1:
            Snapshot.objects.filter(pk=snapshot.pk).update(empresa_id=empresas[0])


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0076_user_perm_estoque_avaria_user_perm_estoque_cedencia_and_more'),
        ('estoque', '0035_movimentacao_ledger_profissional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorateiocustofixo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_rateio_estoque', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='rateiocustofixocompetencia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_rateio_estoque', to='configuracoes.empresa'),
        ),
        migrations.AlterField(
            model_name='rateiocustofixocompetencia',
            name='competencia',
            field=models.DateField(),
        ),
        migrations.RunPython(preencher_empresa_rateio, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='configuracaorateiocustofixo',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa',), name='estoque_rateio_config_empresa_unica'),
        ),
        migrations.AddConstraint(
            model_name='rateiocustofixocompetencia',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'competencia'), name='estoque_rateio_snapshot_empresa_comp'),
        ),
    ]
