# Generated by Django 5.2.6 on 2026-08-02 20:51

import django.db.models.deletion
from django.db import migrations, models


def preencher_empresa_tabelas(apps, schema_editor):
    Tabela = apps.get_model("estoque", "TabelaPreco")
    Venda = apps.get_model("estoque", "VendaRapidaEstoque")
    for tabela in Tabela.objects.filter(empresa__isnull=True):
        empresas = list(
            tabela.itens_preco.exclude(produto__empresa__isnull=True)
            .values_list("produto__empresa_id", flat=True)
            .distinct()[:2]
        )
        if len(empresas) == 1:
            Tabela.objects.filter(pk=tabela.pk).update(empresa_id=empresas[0])
    Venda.objects.filter(tabela_preco_nome="").update(tabela_preco_nome="Preco padrao")


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0076_user_perm_estoque_avaria_user_perm_estoque_cedencia_and_more'),
        ('estoque', '0036_configuracaorateiocustofixo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelapreco',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_preco_estoque', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='vendarapidaestoque',
            name='tabela_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_rapidas', to='estoque.tabelapreco'),
        ),
        migrations.AddField(
            model_name='vendarapidaestoque',
            name='tabela_preco_nome',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.RunPython(preencher_empresa_tabelas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tabelapreco',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='estoque_tabela_preco_empresa_nome'),
        ),
    ]
