# Generated by Django 5.2.6 on 2026-08-03 00:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0036_caixa_empresa_custofixomensal_empresa_and_more'),
        ('clientes', '0013_alter_cliente_documento'),
        ('configuracoes', '0077_empresa_limite_cedencia_sem_aprovacao_and_more'),
        ('estoque', '0037_tabelapreco_empresa_vendarapidaestoque_tabela_preco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoSaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oferta', 'Oferta / brinde'), ('cedencia', 'Cedência')], max_length=20)),
                ('finalidade', models.CharField(choices=[('brinde_comercial', 'Brinde comercial'), ('cortesia_pos_venda', 'Cortesia de pós-venda'), ('uso_interno', 'Uso interno'), ('demonstracao', 'Demonstração'), ('doacao', 'Doação'), ('cedencia_temporaria', 'Cedência temporária'), ('cedencia_definitiva', 'Cedência definitiva'), ('outro', 'Outro')], max_length=30)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('beneficiario_nome', models.CharField(max_length=160)),
                ('campanha', models.CharField(blank=True, max_length=120)),
                ('centro_custo_nome', models.CharField(blank=True, max_length=120)),
                ('documento_autorizacao', models.CharField(blank=True, max_length=120)),
                ('observacao', models.CharField(max_length=240)),
                ('valor_unitario_custo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total_custo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exige_aprovacao', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de aprovação'), ('executada', 'Aprovada e executada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('rejeitado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=240)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_estoque_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_saida_estoque', to='caixa.centrocusto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_saida_estoque', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_saida_estoque', to='configuracoes.empresa')),
                ('movimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao_saida', to='estoque.movimentacaoestoque')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_saida', to='estoque.pontooperacional')),
                ('origem_ubicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_saida', to='estoque.ubicacaoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_saida', to='estoque.produto')),
                ('rejeitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_estoque_rejeitadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_saida_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['empresa', 'status', '-criado_em'], name='idx_sol_saida_emp_status'), models.Index(fields=['tipo', '-criado_em'], name='idx_sol_saida_tipo_data')],
            },
        ),
    ]
