# Generated by Django 5.2.6 on 2026-08-03 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0038_solicitacaosaidaestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaosaidaestoque',
            name='devolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaosaidaestoque',
            name='devolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cedencias_estoque_devolvidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaosaidaestoque',
            name='movimento_retorno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retorno_solicitacao_saida', to='estoque.movimentacaoestoque'),
        ),
        migrations.AddField(
            model_name='solicitacaosaidaestoque',
            name='observacao_devolucao',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='solicitacaosaidaestoque',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de aprovação'), ('executada', 'Aprovada e executada'), ('devolvida', 'Cedência devolvida'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
