# Generated by Django 5.2.6 on 2026-08-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0039_solicitacaosaidaestoque_devolvido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendarapidaestoque',
            name='composicao_kit_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
