# Generated by Django 5.2.6 on 2026-08-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0040_vendarapidaestoque_composicao_kit_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='precificacao_atualizada_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='precificacao_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='precificacao_versao',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
