# Generated by Django 5.2.6 on 2026-08-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0077_empresa_limite_cedencia_sem_aprovacao_and_more'),
        ('estoque', '0042_backfill_snapshots_precificacao_kits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAuditoriaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'Sem divergencias'), ('divergencia', 'Com divergencias'), ('erro', 'Erro de execucao')], max_length=20)),
                ('origem', models.CharField(choices=[('agendada', 'Agendada'), ('manual', 'Manual'), ('sistema', 'Sistema')], default='agendada', max_length=20)),
                ('apenas_ativos', models.BooleanField(default=True)),
                ('total_divergencias', models.PositiveIntegerField(default=0)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execucoes_auditoria_estoque', to='configuracoes.empresa')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['empresa', '-criado_em'], name='idx_audest_emp_criado'), models.Index(fields=['status', '-criado_em'], name='idx_audest_status_criado')],
            },
        ),
    ]
