# Generated by Django 5.2.6 on 2026-08-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0078_fornecedorgarantia_empresa_marcagarantia_empresa_and_more'),
        ('estoque', '0043_execucaoauditoriaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_produto', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='pontooperacional',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pontos_operacionais', to='configuracoes.empresa'),
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pontooperacional',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='categoriaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='estoque_categoria_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='estoque_categoria_legado_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='pontooperacional',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'codigo'), name='estoque_ponto_empresa_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='pontooperacional',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('codigo',), name='estoque_ponto_legado_codigo_unico'),
        ),
    ]
