# Generated by Django 5.2.6 on 2026-08-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0080_parceiroexpedicao_empresa_and_more'),
        ('estoque', '0044_categoriaproduto_empresa_pontooperacional_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoreferencia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos_referencia_estoque', to='configuracoes.empresa'),
        ),
        migrations.AlterField(
            model_name='servicoreferencia',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='servicoreferencia',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='estoque_servico_ref_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='servicoreferencia',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='estoque_servico_ref_legado_nome_unico'),
        ),
    ]
