# Generated by Django 5.2.6 on 2026-08-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0048_produto_classificacao_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_item',
            field=models.CharField(choices=[('produto', 'Produto'), ('peca', 'Peca'), ('consumivel', 'Consumivel'), ('fabricado', 'Produto fabricado / industrializado'), ('servico', 'Servico')], default='produto', max_length=20),
        ),
    ]
