# Generated by Django 5.2.6 on 2026-08-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0049_alter_produto_tipo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada de estoque'), ('transferencia', 'Transferencia'), ('avaria', 'Avaria'), ('perda', 'Perda / extravio'), ('vencimento', 'Vencimento / validade expirada'), ('uso_interno', 'Uso / consumo interno'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('oferta', 'Oferta / brinde'), ('cedencia', 'Cedencia interna'), ('reserva', 'Reserva'), ('consumo_os', 'Consumo em OS'), ('devolucao_reserva', 'Devolucao de reserva'), ('inventario', 'Inventario')], default='transferencia', max_length=20),
        ),
    ]
