# Generated by Django 5.2.6 on 2026-08-06 09:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0049_conciliacaobancaria_descricao_diferenca_and_more'),
        ('configuracoes', '0088_fornecedor_comercial_cnpj'),
        ('estoque', '0050_alter_movimentacaoestoque_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada de estoque'), ('transferencia', 'Transferencia'), ('avaria', 'Avaria'), ('perda', 'Perda / extravio'), ('vencimento', 'Vencimento / validade expirada'), ('uso_interno', 'Uso / consumo interno'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('oferta', 'Oferta / brinde'), ('cedencia', 'Cedencia interna'), ('reserva', 'Reserva'), ('consumo_os', 'Consumo em OS'), ('devolucao_reserva', 'Devolucao de reserva'), ('inventario', 'Inventario'), ('transferencia_interempresa_saida', 'Transferência entre empresas - saída'), ('transferencia_interempresa_entrada', 'Transferência entre empresas - entrada')], default='transferencia', max_length=40),
        ),
        migrations.CreateModel(
            name='TransferenciaEstoqueInterempresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('documento_fiscal', models.CharField(help_text='Chave/número do documento fiscal que autoriza a operação.', max_length=120)),
                ('natureza_operacao', models.CharField(max_length=160)),
                ('data_operacao', models.DateField(default=django.utils.timezone.localdate)),
                ('observacao', models.CharField(blank=True, max_length=240)),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('chave_idempotencia', models.CharField(max_length=120, unique=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_interempresa_entrada', to='estoque.pontooperacional')),
                ('destino_ubicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_interempresa_entrada', to='estoque.ubicacaoestoque')),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_estoque_entrada', to='configuracoes.empresa')),
                ('empresa_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_estoque_saida', to='configuracoes.empresa')),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movimento_entrada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_interempresa_entrada', to='estoque.movimentacaoestoque')),
                ('movimento_saida', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_interempresa_saida', to='estoque.movimentacaoestoque')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_interempresa_saida', to='estoque.pontooperacional')),
                ('origem_ubicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_interempresa_saida', to='estoque.ubicacaoestoque')),
                ('produto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_interempresa_entrada', to='estoque.produto')),
                ('produto_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_interempresa_saida', to='estoque.produto')),
            ],
            options={
                'ordering': ['-data_operacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaEntradaMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('origem', models.CharField(choices=[('xml', 'XML'), ('manual', 'Manual')], default='manual', max_length=12)),
                ('revisada', models.BooleanField(default=False)),
                ('conta_pagar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcela_entrada_mercadoria', to='caixa.contapagar')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_financeiras', to='estoque.entradamercadoria')),
            ],
            options={
                'ordering': ['vencimento', 'id'],
                'constraints': [models.UniqueConstraint(fields=('entrada', 'numero'), name='entrada_parcela_numero_unico')],
            },
        ),
    ]
