# Generated by Django 5.2.6 on 2026-08-06 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0088_fornecedor_comercial_cnpj'),
        ('estoque', '0055_documento_fiscal_conferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='categoria_proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_xml_propostos', to='estoque.categoriaproduto'),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='marca_proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_xml_propostos', to='configuracoes.marcagarantia'),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='margem_lucro_proposta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='margem_minima_proposta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='ncm_proposto',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='nome_proposto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='pendencias_cadastro',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='preco_final_proposto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='rascunho_salvo_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='rascunho_salvo_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rascunhos_produto_xml_salvos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='status_pre_cadastro',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('rascunho', 'Rascunho incompleto'), ('pronto', 'Pronto para aprovação'), ('aprovado', 'Aprovado'), ('nao_aplicavel', 'Produto existente')], default='nao_iniciado', max_length=20),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='sugestoes_cadastro',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itemimportacaoxml',
            name='tipo_item_proposto',
            field=models.CharField(choices=[('produto', 'Produto'), ('peca', 'Peca'), ('consumivel', 'Consumivel'), ('fabricado', 'Produto fabricado / industrializado'), ('servico', 'Servico')], default='produto', max_length=20),
        ),
    ]
