# Generated by Django 5.2.6 on 2025-10-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo_os', models.CharField(default='OS', max_length=10, verbose_name='Prefixo da OS')),
                ('inicio_id_ordem', models.PositiveIntegerField(default=1, verbose_name='Número inicial da OS')),
                ('gerar_numero_automatico', models.BooleanField(default=True, verbose_name='Gerar número automaticamente')),
                ('rodape_relatorio', models.TextField(blank=True, verbose_name='Rodapé dos relatórios')),
            ],
            options={
                'verbose_name': 'Configuração da Ordem de Serviço',
                'verbose_name_plural': 'Configuração da Ordem de Serviço',
            },
        ),
    ]
