# Generated by Django 5.2.6 on 2025-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracaoordemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
