# Generated by Django 5.2.6 on 2026-01-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_sequenciaos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_padrao', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado padrão')),
                ('ddd_padrao', models.CharField(choices=[('11', '11 - São Paulo'), ('12', '12 - São Paulo'), ('13', '13 - São Paulo'), ('14', '14 - São Paulo'), ('15', '15 - São Paulo'), ('16', '16 - São Paulo'), ('17', '17 - São Paulo'), ('18', '18 - São Paulo'), ('19', '19 - São Paulo'), ('21', '21 - Rio de Janeiro'), ('22', '22 - Rio de Janeiro'), ('24', '24 - Rio de Janeiro'), ('27', '27 - Espírito Santo'), ('28', '28 - Espírito Santo'), ('31', '31 - Minas Gerais'), ('32', '32 - Minas Gerais'), ('33', '33 - Minas Gerais'), ('34', '34 - Minas Gerais'), ('35', '35 - Minas Gerais'), ('37', '37 - Minas Gerais'), ('38', '38 - Minas Gerais'), ('41', '41 - Paraná'), ('42', '42 - Paraná'), ('43', '43 - Paraná'), ('44', '44 - Paraná'), ('45', '45 - Paraná'), ('46', '46 - Paraná'), ('47', '47 - Santa Catarina'), ('48', '48 - Santa Catarina'), ('49', '49 - Santa Catarina'), ('51', '51 - Rio Grande do Sul'), ('53', '53 - Rio Grande do Sul'), ('54', '54 - Rio Grande do Sul'), ('55', '55 - Rio Grande do Sul'), ('61', '61 - Distrito Federal'), ('62', '62 - Goiás'), ('63', '63 - Tocantins'), ('64', '64 - Goiás'), ('65', '65 - Mato Grosso'), ('66', '66 - Mato Grosso'), ('67', '67 - Mato Grosso do Sul'), ('68', '68 - Acre'), ('69', '69 - Rondônia'), ('71', '71 - Bahia'), ('73', '73 - Bahia'), ('74', '74 - Bahia'), ('75', '75 - Bahia'), ('77', '77 - Bahia'), ('79', '79 - Sergipe'), ('81', '81 - Pernambuco'), ('82', '82 - Alagoas'), ('83', '83 - Paraíba'), ('84', '84 - Rio Grande do Norte'), ('85', '85 - Ceará'), ('86', '86 - Piauí'), ('87', '87 - Pernambuco'), ('88', '88 - Ceará'), ('89', '89 - Piauí'), ('91', '91 - Pará'), ('92', '92 - Amazonas'), ('93', '93 - Pará'), ('94', '94 - Pará'), ('95', '95 - Roraima'), ('96', '96 - Amapá'), ('97', '97 - Amazonas'), ('98', '98 - Maranhão'), ('99', '99 - Maranhão')], default='11', max_length=2, verbose_name='DDD padrão')),
                ('cliente_cpf_obrigatorio', models.BooleanField(default=True, verbose_name='CPF obrigatório')),
                ('cliente_cnpj_obrigatorio', models.BooleanField(default=True, verbose_name='CNPJ obrigatório')),
                ('cliente_telefone_obrigatorio', models.BooleanField(default=True, verbose_name='Telefone obrigatório')),
                ('cliente_email_obrigatorio', models.BooleanField(default=False, verbose_name='Email obrigatório')),
                ('cliente_endereco_obrigatorio', models.BooleanField(default=False, verbose_name='Endereço obrigatório')),
                ('cliente_cep_obrigatorio', models.BooleanField(default=False, verbose_name='CEP obrigatório')),
                ('ordem_equipamento_obrigatorio', models.BooleanField(default=True, verbose_name='Equipamento obrigatório')),
                ('ordem_marca_obrigatorio', models.BooleanField(default=True, verbose_name='Marca obrigatória')),
                ('ordem_modelo_obrigatorio', models.BooleanField(default=True, verbose_name='Modelo obrigatório')),
                ('ordem_serial_obrigatorio', models.BooleanField(default=False, verbose_name='Nº Série obrigatório')),
                ('ordem_defeito_obrigatorio', models.BooleanField(default=True, verbose_name='Defeito obrigatório')),
                ('ordem_observacoes_obrigatorio', models.BooleanField(default=False, verbose_name='Observações obrigatórias')),
                ('usar_api_cep', models.BooleanField(default=True, verbose_name='Usar API de CEP')),
                ('api_cep_provedor', models.CharField(choices=[('viacep', 'ViaCEP'), ('brasilapi', 'BrasilAPI'), ('awesomeapi', 'AwesomeAPI')], default='viacep', max_length=20, verbose_name='Provedor de API CEP')),
                ('busca_minimo_caracteres', models.PositiveIntegerField(default=3, verbose_name='Mínimo de caracteres para busca')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
