# Generated by Django 5.2.6 on 2026-02-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_configuracaosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaomodulo',
            name='tipo_usuario',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gerente', 'Gerente'), ('atendente', 'Atendente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gerente', 'Gerente'), ('atendente', 'Atendente')], default='atendente', max_length=20),
        ),
    ]
