# Generated by Django 5.2.6 on 2026-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_alter_permissaomodulo_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaomodulo',
            name='tipo_usuario',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gerente', 'Gerente'), ('atendente', 'Atendente'), ('tecnico', 'Tecnico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gerente', 'Gerente'), ('atendente', 'Atendente'), ('tecnico', 'Tecnico')], default='atendente', max_length=20),
        ),
    ]
