# Generated by Django 5.2.6 on 2026-02-21 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_alter_permissaomodulo_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_vendedor',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numero de vendedor deve conter apenas digitos (minimo 2).', regex='^\\d{2,10}$')]),
        ),
    ]
