# Generated by Django 5.2.6 on 2026-02-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0008_fornecedorgarantia_marcagarantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='contrato',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='modalidade_pagamento',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='prazo_pagamento_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='razao_social',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='RegraGarantiaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.CharField(choices=[('celular', 'Celular'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('computador', 'Computador'), ('secador', 'Secador'), ('alisador', 'Alisador'), ('modelador', 'Modelador'), ('escova', 'Escova'), ('ventilador', 'Ventilador'), ('climatizador', 'Climatizador'), ('aspirador', 'Aspirador'), ('cafeteira', 'Cafeteira'), ('outros', 'Outros')], max_length=30)),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modalidade_pagamento', models.CharField(choices=[('faturado', 'Faturado'), ('boleto', 'Boleto'), ('pix', 'PIX'), ('credito_loja', 'Credito em conta loja'), ('outro', 'Outro')], default='faturado', max_length=30)),
                ('prazo_pagamento_dias', models.PositiveIntegerField(default=30)),
                ('ativo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_garantia', to='configuracoes.marcagarantia')),
            ],
            options={
                'ordering': ['marca__nome', 'tipo_produto'],
                'unique_together': {('marca', 'tipo_produto', 'modalidade_pagamento')},
            },
        ),
    ]
