# Generated by Django 5.2.6 on 2026-02-23 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_fornecedorgarantia_cnpj_fornecedorgarantia_contrato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regragarantiamarca',
            options={'ordering': ['marca__nome', 'tipo_produto', '-inicio_vigencia']},
        ),
        migrations.AlterUniqueTogether(
            name='regragarantiamarca',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='regragarantiamarca',
            name='fim_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regragarantiamarca',
            name='inicio_vigencia',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='regragarantiamarca',
            unique_together={('marca', 'tipo_produto', 'modalidade_pagamento', 'inicio_vigencia')},
        ),
    ]
