# Generated by Django 5.2.6 on 2026-02-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0010_alter_regragarantiamarca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='comprovante_pagamento_anexo',
            field=models.FileField(blank=True, null=True, upload_to='fornecedores/comprovantes/'),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='documento_anexo',
            field=models.FileField(blank=True, null=True, upload_to='fornecedores/documentos/'),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='marcagarantia',
            name='procedimentos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fornecedorgarantia',
            name='modalidade_pagamento',
            field=models.CharField(choices=[('transferencia_bancaria', 'Transferencia bancaria'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao_credito', 'Cartao de credito'), ('cartao_debito', 'Cartao de debito'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='transferencia_bancaria', max_length=40),
        ),
        migrations.AlterField(
            model_name='marcagarantia',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marcas', to='configuracoes.fornecedorgarantia'),
        ),
    ]
