# Generated by Django 5.2.6 on 2026-02-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0011_fornecedorgarantia_comprovante_pagamento_anexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcagarantia',
            name='parceira_garantia',
            field=models.BooleanField(default=False),
        ),
    ]
