# Generated by Django 5.2.6 on 2026-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0012_marcagarantia_parceira_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='regragarantiamarca',
            name='valor_mao_obra_tecnico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mao de obra tecnico'),
        ),
        migrations.AlterField(
            model_name='regragarantiamarca',
            name='valor_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor pago'),
        ),
    ]
