# Generated by Django 5.2.6 on 2026-02-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0014_configuracaosistema_mensagens_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('ambos', 'Ambos')], default='ambos', max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=180)),
                ('corpo', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
