# Generated by Django 5.2.6 on 2026-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0016_modelomensagem_padroes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='termos_ordem_servico',
            field=models.TextField(blank=True, default='O equipamento descrito nesta OS sera submetido a analise tecnica e eventual reparo mediante aprovacao do orcamento. O prazo informado e estimado e podera variar conforme complexidade do reparo ou disponibilidade de pecas. Poderao ser utilizadas pecas originais ou compativeis. Pecas substituidas somente serao devolvidas mediante solicitacao previa. Garantia de 90 dias, limitada ao servico executado. Perde-se a garantia em caso de violacao do lacre, intervencao de terceiros, mau uso, queda ou contato com liquido. Apos comunicacao de conclusao, o equipamento devera ser retirado em ate ___ dias. Apos 90 dias sem retirada, podera ser considerado abandonado. Ao assinar esta OS, o cliente declara estar ciente e de acordo com os termos acima, autorizando a abertura do equipamento para diagnostico e reparo. O cliente declara estar ciente de que equipamentos com desgaste, danos previos ou vicios ocultos poderao apresentar agravamento de falhas durante o reparo, nao sendo a assistencia responsavel por defeitos decorrentes de condicoes preexistentes.', verbose_name='Termos e condicoes da Ordem de Servico'),
        ),
    ]
