# Generated by Django 5.2.6 on 2026-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0017_configuracaosistema_termos_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='aliquota_comercio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='aliquota_servico',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='anexo_simples',
            field=models.CharField(blank=True, choices=[('I', 'Anexo I'), ('II', 'Anexo II'), ('III', 'Anexo III'), ('IV', 'Anexo IV'), ('V', 'Anexo V')], max_length=4),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cofins',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='icms',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ipi',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modo_tributario',
            field=models.CharField(choices=[('basico', 'Modo Basico'), ('avancado', 'Modo Avancado')], default='basico', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pis',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_tributario',
            field=models.CharField(choices=[('simples', 'Simples Nacional'), ('presun', 'Lucro Presumido'), ('real', 'Lucro Real')], default='simples', max_length=10),
        ),
    ]
