# Generated by Django 5.2.6 on 2026-03-01 10:45

from django.db import migrations


TIPOS_EQUIPAMENTO_PADRAO = [
    ("celular", "Celular"),
    ("notebook", "Notebook"),
    ("tablet", "Tablet"),
    ("computador", "Computador"),
    ("secador", "Secador"),
    ("alisador", "Alisador"),
    ("modelador", "Modelador"),
    ("escova", "Escova"),
    ("ventilador", "Ventilador"),
    ("climatizador", "Climatizador"),
    ("aspirador", "Aspirador"),
    ("cafeteira", "Cafeteira"),
    ("outros", "Outros"),
]


def seed_tipos_padrao(apps, schema_editor):
    TipoEquipamentoConfig = apps.get_model("configuracoes", "TipoEquipamentoConfig")
    for ordem, (codigo, nome) in enumerate(TIPOS_EQUIPAMENTO_PADRAO):
        TipoEquipamentoConfig.objects.get_or_create(
            codigo=codigo,
            defaults={"nome": nome, "ativo": True, "ordem": ordem},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0019_tipoequipamentoconfig"),
    ]

    operations = [
        migrations.RunPython(seed_tipos_padrao, noop_reverse),
    ]

