# Generated by Django 5.2.6 on 2026-03-01 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0020_seed_tipos_equipamento_padrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='ctps',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='data_demissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='documento_cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='observacoes_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pis_pasep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='regime_contratacao',
            field=models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estagio'), ('freelancer', 'Freelancer'), ('temporario', 'Temporario'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_pessoa',
            field=models.CharField(choices=[('fisica', 'Pessoa Fisica'), ('juridica', 'Pessoa Juridica (ME/PJ)')], default='fisica', max_length=12),
        ),
        migrations.CreateModel(
            name='UsuarioArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('documento', 'Documento'), ('contrato', 'Contrato'), ('certificado', 'Certificado'), ('outro', 'Outro')], default='documento', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('arquivo', models.FileField(upload_to='usuarios/arquivos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_enviados_usuarios', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criacao'), ('edicao', 'Edicao'), ('inativacao', 'Inativacao'), ('reativacao', 'Reativacao'), ('anexo', 'Anexo')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_perfil', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_usuarios_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_evento', '-id'],
            },
        ),
    ]
