# Generated by Django 5.2.6 on 2026-03-02 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0021_alter_user_options_user_cargo_user_ctps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='numero_loja_talao',
            field=models.CharField(default='01', max_length=2, validators=[django.core.validators.RegexValidator(message='Numero da loja deve ter 2 digitos.', regex='^\\d{2}$')], verbose_name='Numero da loja (talao)'),
        ),
    ]
