# Generated by Django 5.2.6 on 2026-03-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0022_configuracaosistema_numero_loja_talao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='backup_retencao_dias',
            field=models.PositiveIntegerField(default=15, verbose_name='Retencao de backups (dias)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='estoque_permitir_negativo',
            field=models.BooleanField(default=True, verbose_name='Permitir saldo negativo no estoque'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='estoque_pre_reserva_exige_saldo',
            field=models.BooleanField(default=False, verbose_name='Exigir saldo para pre-reserva de venda'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='inventario_ciclico_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Periodicidade do inventario ciclico (dias)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='inventario_ultima_execucao',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima execucao do inventario ciclico'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='lgpd_mascarar_documento',
            field=models.BooleanField(default=True, verbose_name='Mascarar documentos em telas de consulta'),
        ),
    ]
