# Generated by Django 5.2.6 on 2026-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0023_configuracaosistema_backup_retencao_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regragarantiamarca',
            name='tipo_produto',
            field=models.CharField(max_length=40),
        ),
    ]
