# Generated by Django 5.2.6 on 2026-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0024_alter_regragarantiamarca_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='endereco',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
