# Generated by Django 5.2.6 on 2026-03-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0025_fornecedorgarantia_cep_fornecedorgarantia_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='dias_bonus_retirada_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='dias_bonus_retirada_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='dias_bonus_retirada_3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='valor_bonus_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='valor_bonus_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='valor_bonus_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='percentual_comissao_peca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='percentual_comissao_servico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_vinculo',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('PJ', 'PJ'), ('FREELANCER', 'Freelancer')], default='FUNCIONARIO', max_length=20),
        ),
    ]
