# Generated by Django 5.2.6 on 2026-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0026_configuracaosistema_dias_bonus_retirada_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='percentual_padrao_desempenho_peca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual padrao de desempenho (pecas)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='percentual_padrao_desempenho_servico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual padrao de desempenho (servicos)'),
        ),
    ]
