# Generated by Django 5.2.6 on 2026-03-17 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0028_user_percentual_comissao_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='backup_retencao_dias',
            field=models.PositiveIntegerField(default=15, verbose_name='Retenção de backups (dias)'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='condicoes_orcamento',
            field=models.TextField(blank=True, default='Validade de 7 dias. Valores sujeitos à aprovação do cliente.'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='inventario_ciclico_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Periodicidade do inventário cíclico (dias)'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='inventario_ultima_execucao',
            field=models.DateField(blank=True, null=True, verbose_name='Última execução do inventário cíclico'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mensagem_orcamento_email',
            field=models.TextField(blank=True, default='Olá {cliente_nome}, seu orçamento da OS {numero_os} está disponível. Valor: {valor_orcamento}. Condições: {condicoes}. Código: {codigo_portal}.'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mensagem_orcamento_whatsapp',
            field=models.TextField(blank=True, default='Olá, {cliente_nome}. Orçamento da OS {numero_os}: {valor_orcamento}. Condições: {condicoes}. Código de acompanhamento: {codigo_portal}.'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mensagem_pronto_email',
            field=models.TextField(blank=True, default='Olá {cliente_nome}, seu equipamento da OS {numero_os} está pronto para retirada. Código: {codigo_portal}.'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mensagem_pronto_whatsapp',
            field=models.TextField(blank=True, default='Olá, {cliente_nome}. Seu equipamento da OS {numero_os} está pronto para retirada. Código: {codigo_portal}.'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='numero_loja_talao',
            field=models.CharField(default='01', max_length=2, validators=[django.core.validators.RegexValidator(message='Número da loja deve ter 2 dígitos.', regex='^\\d{2}$')], verbose_name='Número da loja (talão)'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='percentual_padrao_desempenho_peca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual padrão de desempenho (peças)'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='percentual_padrao_desempenho_servico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual padrão de desempenho (serviços)'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='termos_ordem_servico',
            field=models.TextField(blank=True, default='O equipamento descrito nesta OS será submetido à análise técnica e eventual reparo mediante aprovação do orçamento. O prazo informado é estimado e poderá variar conforme a complexidade do reparo ou disponibilidade de peças. Poderão ser utilizadas peças originais ou compatíveis. Peças substituídas somente serão devolvidas mediante solicitação prévia. Garantia de 90 dias, limitada ao serviço executado. Perde-se a garantia em caso de violação do lacre, intervenção de terceiros, mau uso, queda ou contato com líquido. Após comunicação de conclusão, o equipamento deverá ser retirado em até ___ dias. Após 90 dias sem retirada, poderá ser considerado abandonado. Ao assinar esta OS, o cliente declara estar ciente e de acordo com os termos acima, autorizando a abertura do equipamento para diagnóstico e reparo. O cliente declara estar ciente de que equipamentos com desgaste, danos prévios ou vícios ocultos poderão apresentar agravamento de falhas durante o reparo, não sendo a assistência responsável por defeitos decorrentes de condições preexistentes.', verbose_name='Termos e condições da Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modo_tributario',
            field=models.CharField(choices=[('basico', 'Modo Básico'), ('avancado', 'Modo Avançado')], default='basico', max_length=10),
        ),
        migrations.AlterField(
            model_name='fornecedorgarantia',
            name='modalidade_pagamento',
            field=models.CharField(choices=[('transferencia_bancaria', 'Transferência bancária'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='transferencia_bancaria', max_length=40),
        ),
        migrations.AlterField(
            model_name='permissaomodulo',
            name='tipo_usuario',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gerente', 'Gerente'), ('atendente', 'Atendente'), ('tecnico', 'Técnico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regragarantiamarca',
            name='modalidade_pagamento',
            field=models.CharField(choices=[('faturado', 'Faturado'), ('boleto', 'Boleto'), ('pix', 'PIX'), ('credito_loja', 'Crédito em conta loja'), ('outro', 'Outro')], default='faturado', max_length=30),
        ),
        migrations.AlterField(
            model_name='regragarantiamarca',
            name='valor_mao_obra_tecnico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mão de obra técnico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_vendedor',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Número de vendedor deve conter apenas dígitos (mínimo 2).', regex='^\\d{2,10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='regime_contratacao',
            field=models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('freelancer', 'Freelancer'), ('temporario', 'Temporário'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_pessoa',
            field=models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica (ME/PJ)')], default='fisica', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gerente', 'Gerente'), ('atendente', 'Atendente'), ('tecnico', 'Técnico')], default='atendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_vinculo',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionário'), ('PJ', 'PJ'), ('FREELANCER', 'Freelancer')], default='FUNCIONARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariolog',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('inativacao', 'Inativação'), ('reativacao', 'Reativação'), ('anexo', 'Anexo')], max_length=20),
        ),
    ]
