# Generated by Django 5.2.6 on 2026-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0030_configuracaosistema_usar_confirmacao_assinatura_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='logos/pdf/'),
        ),
    ]
