# Generated by Django 5.2.6 on 2026-04-12 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0032_user_funcoes_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='layout_os_data_fonte_pt',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)], verbose_name='Fonte das datas no bloco de assinatura (pt)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='layout_os_digital_exibir_validacao',
            field=models.BooleanField(default=True, verbose_name='Exibir bloco de validação na OS digital'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='layout_os_frente_espaco_assinaturas_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(2)], verbose_name='Ajuste de espaço das assinaturas na frente (cm)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='layout_os_impressao',
            field=models.CharField(choices=[('compacto', 'Compacto'), ('padrao', 'Padrão'), ('amplo', 'Amplo')], default='padrao', max_length=20, verbose_name='Preset de layout da OS impressa'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='layout_os_verso_espaco_assinatura_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(2)], verbose_name='Ajuste de espaço da assinatura no verso (cm)'),
        ),
    ]
