# Generated by Django 5.2.6 on 2026-04-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0033_configuracaosistema_layout_os_data_fonte_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='layout_documentos_preset',
            field=models.CharField(choices=[('classico', 'Clássico'), ('clean', 'Clean'), ('tecnico', 'Técnico')], default='clean', max_length=20, verbose_name='Preset visual dos documentos (OS/Relatório/Orçamento)'),
        ),
    ]
