# Generated by Django 5.2.6 on 2026-04-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0034_configuracaosistema_layout_documentos_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='layout_documentos_preset',
            field=models.CharField(choices=[('classico', 'Clássico'), ('clean', 'Clean'), ('tecnico', 'Técnico'), ('compacto', 'Compacto'), ('executivo', 'Executivo')], default='clean', max_length=20, verbose_name='Preset visual dos documentos (OS/Relatório/Orçamento)'),
        ),
    ]
