# Generated by Django 5.2.6 on 2026-04-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0038_user_perm_caixa_excluir_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm_caixa_aplicar_desconto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_orcamento_aplicar_desconto',
            field=models.BooleanField(default=False),
        ),
    ]
