# Generated by Django 5.2.6 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0043_user_perm_fase3_ordens_orcamentos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParceiroExpedicao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120, unique=True, verbose_name="Nome")),
                ("contato", models.CharField(blank=True, max_length=120, verbose_name="Contato")),
                ("telefone", models.CharField(blank=True, max_length=30, verbose_name="Telefone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-mail")),
                ("observacoes", models.TextField(blank=True, verbose_name="Observacoes")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Parceiro de expedicao",
                "verbose_name_plural": "Parceiros de expedicao",
                "ordering": ["nome"],
            },
        ),
    ]
