# Generated by Django 5.2.6 on 2026-05-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0045_user_perm_estoque_granulares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parceiroexpedicao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='parceiroexpedicao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parceiroexpedicao',
            name='contato',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='parceiroexpedicao',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='parceiroexpedicao',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='parceiroexpedicao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parceiroexpedicao',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
