# Generated by Django 5.2.6 on 2026-05-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0046_alter_parceiroexpedicao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoEmpresaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LinhaAtuacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='configuracoes.segmentoempresacatalogo')),
            ],
            options={
                'ordering': ['segmento__ordem', 'ordem', 'nome'],
                'unique_together': {('segmento', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='SetupInicialSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(blank=True, choices=[('assistencia_tecnica', 'Assistencia tecnica'), ('oficina_mecanica', 'Oficina mecanica')], max_length=40)),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_inicial', to='configuracoes.empresa')),
                ('linhas_atuacao', models.ManyToManyField(blank=True, related_name='setups', to='configuracoes.linhaatuacaocatalogo')),
            ],
            options={
                'verbose_name': 'Setup inicial do sistema',
                'verbose_name_plural': 'Setup inicial do sistema',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipamentoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_equipamento', to='configuracoes.linhaatuacaocatalogo')),
            ],
            options={
                'ordering': ['linha__segmento__ordem', 'linha__ordem', 'ordem', 'nome'],
                'unique_together': {('linha', 'nome')},
            },
        ),
    ]
