# Generated by Django 5.2.6 on 2026-05-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0047_segmentoempresacatalogo_linhaatuacaocatalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoequipamentoconfig',
            name='codigo',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
