# Generated by Django 5.2.6 on 2026-05-13 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0048_alter_setupinicialsistema_tipo_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80)),
                ('origem', models.CharField(choices=[('ui', 'Interface'), ('comando', 'Comando'), ('api', 'API')], default='ui', max_length=20)),
                ('alvo', models.CharField(blank=True, max_length=120)),
                ('antes_json', models.TextField(blank=True)),
                ('depois_json', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_configuracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
