# Generated by Django 5.2.6 on 2026-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0049_configuracaoauditoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegraSLAAlerta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("os_sem_movimentacao", "OS sem movimentação"),
                            ("orcamento_sem_resposta", "Orçamento sem resposta"),
                            ("peca_reservada_vencendo", "Peça reservada vencendo"),
                            ("equipamento_pronto_parado", "Equipamento pronto há muitos dias"),
                            ("parceiro_externo_atrasado", "Parceiro externo atrasado"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("prazo_valor", models.PositiveIntegerField(default=2)),
                (
                    "prazo_unidade",
                    models.CharField(choices=[("dias", "Dias"), ("horas", "Horas")], default="dias", max_length=10),
                ),
                (
                    "severidade",
                    models.CharField(
                        choices=[("baixa", "Baixa"), ("media", "Média"), ("alta", "Alta"), ("critica", "Crítica")],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("responsavel_padrao", models.CharField(blank=True, max_length=120)),
                ("acao_sugerida", models.CharField(blank=True, max_length=220)),
                (
                    "canal_notificacao",
                    models.CharField(
                        choices=[("painel", "Painel"), ("email", "E-mail"), ("whatsapp", "WhatsApp"), ("nenhum", "Nenhum")],
                        default="painel",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.CharField(blank=True, max_length=220)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Regra de SLA",
                "verbose_name_plural": "Regras de SLA",
                "ordering": ["codigo"],
            },
        ),
    ]
