# Generated by Django 5.2.6 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0050_regraslaalerta"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="garantia_padrao_peca_dias",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="garantia_padrao_servico_dias",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="garantia_reincidencia_janela_dias",
            field=models.PositiveIntegerField(default=180),
        ),
    ]
