# Generated by Django 5.2.6 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0051_configuracaosistema_garantia_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegracaoEventoLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("canal", models.CharField(choices=[("webhook", "Webhook"), ("email", "E-mail"), ("whatsapp", "WhatsApp"), ("sistema", "Sistema")], max_length=20)),
                ("evento", models.CharField(max_length=80)),
                ("status", models.CharField(choices=[("sucesso", "Sucesso"), ("falha", "Falha")], max_length=20)),
                ("destino", models.CharField(blank=True, max_length=220)),
                ("payload_json", models.TextField(blank=True)),
                ("resposta", models.CharField(blank=True, max_length=220)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
    ]
