# Generated by Django 5.2.6 on 2026-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0053_modelomensagem_evento_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='antifraude_desconto_critico_percentual',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='antifraude_exigir_dupla_confirmacao_desconto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='antifraude_exigir_dupla_confirmacao_exclusao_pagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='antifraude_motivo_minimo_caracteres',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
