# Generated by Django 5.2.6 on 2026-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0054_configuracaosistema_antifraude_desconto_critico_percentual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='condicoes_orcamento',
            field=models.TextField(blank=True, default='Validade de 7 dias. Valores sujeitos Ã\xa0 aprovação do cliente.'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='layout_documentos_preset',
            field=models.CharField(choices=[('classico', 'Clássico'), ('clean', 'Clean'), ('tecnico', 'Técnico'), ('parceiro', 'Parceiro'), ('compacto', 'Compacto'), ('executivo', 'Executivo')], default='clean', max_length=20, verbose_name='Preset visual dos documentos (OS/Relatório/Orçamento)'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='termos_ordem_servico',
            field=models.TextField(blank=True, default='O equipamento descrito nesta OS será submetido Ã\xa0 análise técnica e eventual reparo mediante aprovação do orçamento. O prazo informado é estimado e poderá variar conforme a complexidade do reparo ou disponibilidade de peças. Poderão ser utilizadas peças originais ou compatíveis. Peças substituídas somente serão devolvidas mediante solicitação prévia. Garantia de 90 dias, limitada ao serviço executado. Perde-se a garantia em caso de violação do lacre, intervenção de terceiros, mau uso, queda ou contato com líquido. Após comunicação de conclusão, o equipamento deverá ser retirado em até ___ dias. Após 90 dias sem retirada, poderá ser considerado abandonado. Ao assinar esta OS, o cliente declara estar ciente e de acordo com os termos acima, autorizando a abertura do equipamento para diagnóstico e reparo. O cliente declara estar ciente de que equipamentos com desgaste, danos prévios ou vícios ocultos poderão apresentar agravamento de falhas durante o reparo, não sendo a assistência responsável por defeitos decorrentes de condições preexistentes.', verbose_name='Termos e condições da Ordem de Serviço'),
        ),
    ]
