# Generated by Django 5.2.6 on 2026-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0055_alter_configuracaosistema_condicoes_orcamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='estoque_reserva_os_validade_dias',
            field=models.PositiveIntegerField(default=3, verbose_name='Validade da reserva automatica de peca na OS (dias)'),
        ),
    ]
