# Generated by Django 5.2.6 on 2026-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0060_configuracaosistema_sla_dias_os_sem_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='estoque_metodo_custo',
            field=models.CharField(choices=[('pmp', 'PMP (custo medio ponderado)'), ('peps', 'PEPS')], default='pmp', max_length=10, verbose_name='Metodo de custo do estoque'),
        ),
        migrations.AlterField(
            model_name='configuracaoauditoria',
            name='origem',
            field=models.CharField(choices=[('ui', 'Interface'), ('comando', 'Comando'), ('api', 'API'), ('recuperacao_local', 'Recuperação local')], default='ui', max_length=20),
        ),
    ]
