# Generated by Django 5.2.6 on 2026-07-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0061_configuracaosistema_estoque_metodo_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='celular_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
