# Generated by Django 5.2.6 on 2026-07-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0062_empresa_bairro_empresa_celular_whatsapp_empresa_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='enviar_whatsapp_abertura_os',
            field=models.BooleanField(default=True, verbose_name='Enviar WhatsApp automatico na abertura da OS'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='mensagem_abertura_whatsapp',
            field=models.TextField(blank=True, default='Ola, {cliente_nome}. Sua OS {numero_os} foi registrada com sucesso.\n\nEquipamento: {equipamento_resumo}\nPDF da ordem: {link_ordem_pdf}\nConfirmacao/assinatura digital: {link_confirmacao}\n\nSe nao conseguir assinar pelo link, podemos imprimir para assinatura presencial.'),
        ),
    ]
