# Generated by Django 5.2.6 on 2026-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0063_configuracaosistema_enviar_whatsapp_abertura_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='enviar_whatsapp_abertura_os',
            field=models.BooleanField(default=True, verbose_name='Enviar WhatsApp automático na abertura da OS'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mensagem_abertura_whatsapp',
            field=models.TextField(blank=True, default='Olá, {cliente_nome}. Sua OS {numero_os} foi registrada com sucesso.\n\nEquipamento: {equipamento_resumo}\nPDF da ordem: {link_ordem_pdf}\nConfirmação/assinatura digital: {link_confirmacao}\n\nSe não conseguir assinar pelo link, podemos imprimir para assinatura presencial.'),
        ),
    ]
