# Generated by Django 5.2.6 on 2026-07-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0065_configuracaosistema_estoque_venda_mostrador_codigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='comissao_aplicar_pecas',
            field=models.BooleanField(default=False, verbose_name='Permitir comissão sobre peças na OS'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='comissao_bonus_retirada_ativo',
            field=models.BooleanField(default=False, verbose_name='Usar bônus por retirada rápida'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='comissao_criterio_os',
            field=models.CharField(choices=[('pronto_contactado', 'OS pronta/contactada'), ('entregue', 'OS entregue/concluida')], default='pronto_contactado', max_length=24, verbose_name='Critério da comissão técnica'),
        ),
    ]
