# Generated by Django 5.2.6 on 2026-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0066_configuracaosistema_comissao_aplicar_pecas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='comissao_bonus_produto_ativo',
            field=models.BooleanField(default=True, verbose_name='Usar bônus comercial por produto na venda mostrador'),
        ),
    ]
