# Generated by Django 5.2.6 on 2026-07-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0069_fornecedorgarantia_municipio_fornecedorgarantia_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='documentos_exigidos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='email_cobranca',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='portal_garantia_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='procedimento_cobranca',
            field=models.TextField(blank=True),
        ),
    ]
