# Generated by Django 5.2.6 on 2026-07-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0071_configuracaosistema_backup_diretorio_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_aprovacao',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir quadro de aprovação'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_condicoes',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir condições comerciais'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_email_cliente',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir e-mail do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_numero_serie',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir número de série'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_peritagem',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir peritagem'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_assinaturas',
            field=models.BooleanField(default=True, verbose_name='OS: exibir bloco de assinaturas'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_documento_cliente',
            field=models.BooleanField(default=True, verbose_name='OS: exibir documento do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_email_cliente',
            field=models.BooleanField(default=True, verbose_name='OS: exibir e-mail do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_endereco_cliente',
            field=models.BooleanField(default=True, verbose_name='OS: exibir endereço e CEP do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_numero_serie',
            field=models.BooleanField(default=True, verbose_name='OS: exibir número de série'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_peritagem',
            field=models.BooleanField(default=True, verbose_name='OS: exibir peritagem'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_termos',
            field=models.BooleanField(default=True, verbose_name='OS: exibir termos e condições'),
        ),
    ]
