# Generated by Django 5.2.6 on 2026-07-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0072_configuracaosistema_pdf_orcamento_exibir_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_acessorios',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir acessórios'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_email_cliente',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir e-mail do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_numero_serie',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir número de série'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_peritagem',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir peritagem'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_servicos_pecas',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir serviços e peças'),
        ),
    ]
