# Generated by Django 5.2.6 on 2026-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0073_configuracaosistema_pdf_relatorio_exibir_acessorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_acessorios',
            field=models.BooleanField(default=True, verbose_name='OS: exibir acessórios'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_data_compra',
            field=models.BooleanField(default=False, verbose_name='OS: exibir data de compra'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_defeito',
            field=models.BooleanField(default=True, verbose_name='OS: exibir defeito reclamado'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_local_armazenamento',
            field=models.BooleanField(default=False, verbose_name='OS: exibir local de armazenamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_marca_equipamento',
            field=models.BooleanField(default=True, verbose_name='OS: exibir marca do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_modelo_equipamento',
            field=models.BooleanField(default=True, verbose_name='OS: exibir modelo do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_nome_cliente',
            field=models.BooleanField(default=True, verbose_name='OS: exibir nome do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_numero_nota_fiscal',
            field=models.BooleanField(default=False, verbose_name='OS: exibir número da nota fiscal'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_referencia_parceiro',
            field=models.BooleanField(default=False, verbose_name='OS: exibir referência de parceiro'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_telefone_cliente',
            field=models.BooleanField(default=True, verbose_name='OS: exibir telefone do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_tipo_equipamento',
            field=models.BooleanField(default=True, verbose_name='OS: exibir tipo do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_tipo_reparo',
            field=models.BooleanField(default=True, verbose_name='OS: exibir tipo da OS'),
        ),
    ]
