# Generated by Django 5.2.6 on 2026-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0074_configuracaosistema_pdf_os_exibir_acessorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_acessorios',
            field=models.BooleanField(default=False, verbose_name='Orçamento: exibir acessórios'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_defeito',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir defeito reclamado'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_documento_cliente',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir documento do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_marca_equipamento',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir marca do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_modelo_equipamento',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir modelo do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_nome_cliente',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir nome do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_origem_cliente',
            field=models.BooleanField(default=False, verbose_name='Orçamento: exibir origem do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_telefone_cliente',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir telefone do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_tipo_equipamento',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir tipo do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_orcamento_exibir_tipo_reparo',
            field=models.BooleanField(default=True, verbose_name='Orçamento: exibir tipo da OS'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_classificacao_retorno',
            field=models.BooleanField(default=False, verbose_name='OS: exibir classificação do retorno'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_manutencao_preventiva',
            field=models.BooleanField(default=False, verbose_name='OS: exibir manutenção preventiva sugerida'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_origem_cliente',
            field=models.BooleanField(default=False, verbose_name='OS: exibir origem do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_os_exibir_os_origem_garantia',
            field=models.BooleanField(default=False, verbose_name='OS: exibir OS original da garantia'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_datas_movimento',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir datas de entrada e saída'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_defeito',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir defeito reclamado'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_documento_cliente',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir documento do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_local_armazenamento',
            field=models.BooleanField(default=False, verbose_name='Relatório: exibir local de armazenamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_marca_equipamento',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir marca do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_modelo_equipamento',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir modelo do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_nome_cliente',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir nome do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_origem_cliente',
            field=models.BooleanField(default=False, verbose_name='Relatório: exibir origem do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_responsaveis',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir atendente e técnico'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_telefone_cliente',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir telefone do cliente'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_tipo_equipamento',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir tipo do equipamento'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_tipo_reparacao',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir tipo de reparação'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pdf_relatorio_exibir_tipo_reparo',
            field=models.BooleanField(default=True, verbose_name='Relatório: exibir tipo da OS'),
        ),
    ]
