# Generated by Django 5.2.6 on 2026-08-02 20:24

from django.db import migrations, models


def preservar_permissoes_estoque(apps, schema_editor):
    User = apps.get_model("configuracoes", "User")
    User.objects.filter(perm_estoque_ajuste_manual=True).update(
        perm_estoque_avaria=True,
        perm_estoque_oferta=True,
        perm_estoque_cedencia=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0075_configuracaosistema_pdf_orcamento_exibir_acessorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm_estoque_avaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_estoque_cedencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_estoque_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preservar_permissoes_estoque, migrations.RunPython.noop),
    ]
