# Generated by Django 5.2.6 on 2026-08-03 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0076_user_perm_estoque_avaria_user_perm_estoque_cedencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_cedencia_sem_aprovacao',
            field=models.DecimalField(decimal_places=2, default=250, help_text='Custo total máximo que pode ser cedido sem aprovação gerencial.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_oferta_sem_aprovacao',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Custo total máximo que pode ser oferecido sem aprovação gerencial.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
