# Generated by Django 5.2.6 on 2026-08-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0077_empresa_limite_cedencia_sem_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorgarantia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores_garantia', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='marcagarantia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marcas_garantia', to='configuracoes.empresa'),
        ),
        migrations.AlterField(
            model_name='fornecedorgarantia',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='marcagarantia',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='fornecedorgarantia',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='config_fornecedor_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='fornecedorgarantia',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='config_fornecedor_legado_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='marcagarantia',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='config_marca_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='marcagarantia',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='config_marca_legado_nome_unico'),
        ),
    ]
