# Generated by Django 5.2.6 on 2026-08-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0079_backfill_empresa_catalogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiroexpedicao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parceiros_expedicao', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='tipoequipamentoconfig',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_equipamento_config', to='configuracoes.empresa'),
        ),
        migrations.AlterField(
            model_name='parceiroexpedicao',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tipoequipamentoconfig',
            name='codigo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tipoequipamentoconfig',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='parceiroexpedicao',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='config_parceiro_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='parceiroexpedicao',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='config_parceiro_legado_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='tipoequipamentoconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'codigo'), name='config_tipo_eq_empresa_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='tipoequipamentoconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='config_tipo_eq_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='tipoequipamentoconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('codigo',), name='config_tipo_eq_legado_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='tipoequipamentoconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='config_tipo_eq_legado_nome_unico'),
        ),
    ]
