# Generated by Django 5.2.6 on 2026-08-03 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0081_backfill_empresa_catalogos_operacionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='configuracoes.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['empresa__nome', 'usuario__username'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='config_usuario_empresa_unico'), models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('usuario',), name='config_usuario_empresa_padrao_unico')],
            },
        ),
    ]
