# Generated by Django 5.2.6 on 2026-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0089_configuracaosistema_pdf_relatorio_modo_resumido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm_caixa_conciliar_banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_caixa_fechar_banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_caixa_gerir_capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_caixa_gerir_cartoes_corporativos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_caixa_importar_extrato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_os_estornar_custo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_os_registrar_custo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_os_ver_custos',
            field=models.BooleanField(default=False),
        ),
    ]
