# Generated by Django 5.2.6 on 2026-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0090_user_perm_caixa_conciliar_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm_caixa_administrar_plano_contas',
            field=models.BooleanField(default=False),
        ),
    ]
