# Generated by Django 5.2.6 on 2026-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0091_user_perm_caixa_administrar_plano_contas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm_caixa_corrigir_lancamentos',
            field=models.BooleanField(default=False),
        ),
    ]
