# Generated by Django 5.2.6 on 2026-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0092_user_perm_caixa_corrigir_lancamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='google_avaliacao_url',
            field=models.URLField(blank=True, help_text='Usado somente na versão opcional do relatório técnico com pedido de avaliação.', max_length=500, verbose_name='Link direto para avaliação no Google'),
        ),
    ]
