"""
Django settings for assistencia project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-key-change-in-production")
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    "crispy_forms",
    "crispy_bootstrap5",
    'widget_tweaks',

    # nosso app
    'configuracoes',
    'core',
    'estoque',
    'clientes',
    'ordens',
    'orcamentos',
    'caixa',
    'agenda',
    'fiscal',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'configuracoes.middleware.TenantContextMiddleware',
    'configuracoes.middleware.SetupInicialMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'assistencia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'configuracoes.context_processors.empresa_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'assistencia.wsgi.application'


# Database
DB_ENGINE = os.getenv("DJANGO_DB_ENGINE", "sqlite").strip().lower()
DB_CONN_MAX_AGE_DEFAULT = "0" if DEBUG else "60"

if DB_ENGINE == "postgres":
    required_envs = [
        "DJANGO_DB_NAME",
        "DJANGO_DB_USER",
        "DJANGO_DB_PASSWORD",
        "DJANGO_DB_HOST",
    ]
    missing_envs = [env_name for env_name in required_envs if not os.getenv(env_name)]
    if missing_envs:
        raise ImproperlyConfigured(
            "Variaveis de ambiente ausentes para PostgreSQL: " + ", ".join(missing_envs)
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DJANGO_DB_NAME"),
            'USER': os.getenv("DJANGO_DB_USER"),
            'PASSWORD': os.getenv("DJANGO_DB_PASSWORD"),
            'HOST': os.getenv("DJANGO_DB_HOST"),
            'PORT': os.getenv("DJANGO_DB_PORT", "5432"),
            'CONN_MAX_AGE': int(os.getenv("DJANGO_DB_CONN_MAX_AGE", DB_CONN_MAX_AGE_DEFAULT)),
            'CONN_HEALTH_CHECKS': os.getenv("DJANGO_DB_CONN_HEALTH_CHECKS", "1") == "1",
            'OPTIONS': {
                'sslmode': os.getenv("DJANGO_DB_SSLMODE", "prefer"),
                'connect_timeout': int(os.getenv("DJANGO_DB_CONNECT_TIMEOUT", "5")),
                'application_name': os.getenv("DJANGO_DB_APP_NAME", "assistencia_django"),
            },
        }
    }
elif DB_ENGINE == "sqlite":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured("DJANGO_DB_ENGINE invalido. Use 'sqlite' ou 'postgres'.")


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'assistencia.password_validators.PasswordComplexityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "core/static",  # CORRIGIDO - aponta para core/static
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # Adicionado para collectstatic
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ConfiguraÃ§Ãµes de autenticaÃ§Ã£o
LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'core:login'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'configuracoes.User'
RUNNING_TESTS = "test" in sys.argv
SETUP_INICIAL_GATE_ENABLED = os.getenv(
    "DJANGO_SETUP_GATE_ENABLED",
    "0" if RUNNING_TESTS else "1",
) == "1"
TENANT_CONTEXT_ENABLED = os.getenv("DJANGO_TENANT_CONTEXT_ENABLED", "1") == "1"

# Email / notificacoes
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "1") == "1"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@assistencia.local")

# Security (production-safe defaults when DEBUG=False)
if not DEBUG:
    if SECRET_KEY == "django-insecure-dev-key-change-in-production":
        raise ImproperlyConfigured("Defina DJANGO_SECRET_KEY em producao.")
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("Defina DJANGO_ALLOWED_HOSTS em producao.")
    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured("Defina DJANGO_CSRF_TRUSTED_ORIGINS em producao.")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = os.getenv("DJANGO_X_FRAME_OPTIONS", "DENY")
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
