# Generated by Django 5.2.6 on 2026-03-15 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0008_alter_cliente_telefone'),
        ('ordens', '0022_servicopeca_produto_estoque_and_consumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaBloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=160)),
                ('tecnico', models.ForeignKey(blank=True, help_text='Deixe vazio para bloqueio global.', limit_choices_to={'is_active': True, 'tipo_usuario__in': ['tecnico', 'atendente']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_bloqueios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('nome_cliente_avulso', models.CharField(blank=True, max_length=120)),
                ('telefone_contato', models.CharField(blank=True, max_length=30)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('origem', models.CharField(choices=[('interno', 'Interno'), ('publico', 'Publico')], default='interno', max_length=20)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado'), ('falta', 'Falta')], default='agendado', max_length=20)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='ordens.ordemservico')),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo_usuario__in': ['tecnico', 'atendente']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgendaDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=60)),
                ('ativo', models.BooleanField(default=True)),
                ('tecnico', models.ForeignKey(limit_choices_to={'is_active': True, 'tipo_usuario__in': ['tecnico', 'atendente']}, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tecnico__username', 'dia_semana', 'hora_inicio'],
                'unique_together': {('tecnico', 'dia_semana', 'hora_inicio', 'hora_fim')},
            },
        ),
    ]
