# Generated by Django 5.2.6 on 2026-01-18 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('tipo_reparacao', models.CharField(blank=True, choices=[('substituicao', 'Substituição de Peças'), ('reparacao_sem_pecas', 'Reparação sem Peças'), ('nada', 'Nada Efetuado'), ('recusado_preco', 'Devolvido - Recusado (Preço)'), ('recusado_tempo', 'Devolvido - Recusado (Tempo)')], max_length=30, null=True)),
                ('tipo_equipamento', models.CharField(choices=[('celular', 'Celular'), ('notebook', 'Notebook'), ('tablet', 'Tablet'), ('computador', 'Computador'), ('secador', 'Secador'), ('alisador', 'Alisador'), ('modelador', 'Modelador'), ('escova', 'Escova'), ('ventilador', 'Ventilador'), ('climatizador', 'Climatizador'), ('aspirador', 'Aspirador'), ('cafeteira', 'Cafeteira'), ('outros', 'Outros')], max_length=20)),
                ('marca_equipamento', models.CharField(max_length=50)),
                ('modelo_equipamento', models.CharField(max_length=50)),
                ('numero_serie_equipamento', models.CharField(blank=True, max_length=50)),
                ('local_armazenamento', models.CharField(blank=True, max_length=200)),
                ('defeito', models.TextField()),
                ('acessorios', models.TextField(blank=True)),
                ('tipo_reparo', models.CharField(choices=[('Garantia', 'Garantia'), ('Fora de Garantia', 'Fora de Garantia'), ('Garantia de serviço', 'Garantia de serviço')], max_length=20)),
                ('status', models.CharField(choices=[('diagnosticar', 'Diagnosticar'), ('pendente_tecnico', 'Pendente Técnico'), ('pendente_marca', 'Pendente Marca'), ('pendente_pecas', 'Pendente Peças'), ('pendente_orcamento', 'Pendente Orçamento'), ('orcamentado', 'Orçamentado'), ('autorizado', 'Autorizado'), ('recusado', 'Recusado'), ('em_andamento', 'Em Andamento'), ('pronto_contactado', 'Pronto Contactado'), ('pronto_contactar', 'Pronto Contactar'), ('concluida', 'Concluída')], default='diagnosticar', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('peritagem', models.TextField(blank=True)),
                ('relatorio_tecnico', models.TextField(blank=True, null=True)),
                ('fechada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='clientes.cliente')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'atendente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('criada', 'Ordem criada'), ('diagnosticar', 'Diagnosticar'), ('bancada', 'Bancada'), ('reparo', 'Reparo em andamento'), ('pendente_pecas', 'Pendente peças'), ('pendente_cliente', 'Pendente cliente'), ('pendente_marca', 'Pendente marca'), ('orcamentado', 'Orçamentado'), ('pronto_contactado', 'Pronto contactado'), ('devolucao', 'Devolução sem reparação'), ('concluida', 'Concluído')], default='criada', max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_trabalho', to='ordens.ordemservico')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('peca', 'Peça')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_pecas', to='ordens.ordemservico')),
            ],
        ),
    ]
