# Generated by Django 5.2.6 on 2026-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_linhatrabalho_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('diagnosticar', 'Diagnosticar'), ('bancada', 'Bancada'), ('reparo', 'Reparo em andamento'), ('pendente_tecnico', 'Pendente Técnico'), ('pendente_cliente', 'Pendente cliente'), ('pendente_marca', 'Pendente Marca'), ('pendente_pecas', 'Pendente Peças'), ('pendente_orcamento', 'Pendente Orçamento'), ('orcamentado', 'Orçamentado'), ('autorizado', 'Autorizado'), ('recusado', 'Recusado'), ('devolucao', 'Devolução sem reparação'), ('em_andamento', 'Em Andamento'), ('pronto_contactado', 'Pronto Contactado'), ('pronto_contactar', 'Pronto Contactar'), ('concluida', 'Concluída')], default='diagnosticar', max_length=20),
        ),
    ]
