# Generated by Django 5.2.6 on 2026-02-20 12:40

import django.db.models.deletion
import random
import string
from django.conf import settings
from django.db import migrations, models


def popular_codigos_portal(apps, schema_editor):
    OrdemServico = apps.get_model('ordens', 'OrdemServico')
    usados = set(
        OrdemServico.objects.exclude(codigo_portal__isnull=True)
        .exclude(codigo_portal='')
        .values_list('codigo_portal', flat=True)
    )
    for ordem in OrdemServico.objects.all().only('id', 'codigo_portal'):
        if ordem.codigo_portal:
            continue
        codigo = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
        while codigo in usados:
            codigo = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
        usados.add(codigo)
        ordem.codigo_portal = codigo
        ordem.save(update_fields=['codigo_portal'])


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_alter_ordemservico_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='codigo_portal',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.RunPython(popular_codigos_portal, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ordemservico',
            name='codigo_portal',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='NotificacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('orcamento', 'Orcamento'), ('pronto', 'Equipamento pronto'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('canal', models.CharField(choices=[('sistema', 'Sistema'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='sistema', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('destinatario', models.CharField(blank=True, max_length=120)),
                ('mensagem', models.TextField()),
                ('erro', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='ordens.ordemservico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_ordem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
