# Generated by Django 5.2.6 on 2026-02-22 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0008_fornecedorgarantia_marcagarantia'),
        ('ordens', '0005_alter_ordemservico_tecnico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='marca_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='configuracoes.marcagarantia'),
        ),
    ]
