# Generated by Django 5.2.6 on 2026-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0006_ordemservico_marca_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='notas_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
