# Generated by Django 5.2.6 on 2026-02-25 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0007_ordemservico_data_compra_ordemservico_notas_internas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_criados', to=settings.AUTH_USER_MODEL)),
                ('encerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_encerrados', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='ordens.ordemservico')),
            ],
            options={
                'ordering': ['-ativo', '-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponivel'), ('orcamentado', 'Orcamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Transito')], default='contactar', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_compra', to='ordens.ordemservico')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponivel'), ('orcamentado', 'Orcamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Transito')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='ordens.pedidocompra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_pedido_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
