# Generated by Django 5.2.6 on 2026-02-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0008_ordemalerta_pedidocompra_pedidocompralinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='numero_oc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='tipo_peca',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='PedidoCompraFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ordens/pedidos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordens.pedidocompra')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
