# Generated by Django 5.2.6 on 2026-02-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0009_pedidocompra_numero_oc_pedidocompra_tipo_peca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponivel'), ('orcamentado', 'Orcamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Transito')], default='contactar', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidocompralinha',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponivel'), ('orcamentado', 'Orcamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Transito')], max_length=30),
        ),
    ]
