# Generated by Django 5.2.6 on 2026-02-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0010_alter_pedidocompra_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaocliente',
            name='assunto',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
