# Generated by Django 5.2.6 on 2026-02-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0012_ordemservico_confirmacao_campos_e_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponivel'), ('orcamentado', 'Orcamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Transito'), ('fechado', 'Fechado')], default='contactar', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidocompralinha',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponivel'), ('orcamentado', 'Orcamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Transito'), ('fechado', 'Fechado')], max_length=30),
        ),
    ]
