# Generated by Django 5.2.6 on 2026-02-26 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0013_alter_pedidocompra_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('alteracao_status', 'Alteracao de status'), ('confirmacao', 'Confirmacao'), ('edicao_critica', 'Edicao critica'), ('cancelamento', 'Cancelamento')], max_length=30)),
                ('descricao', models.TextField()),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_os', to='ordens.ordemservico')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_operacionais_os', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_evento', '-id'],
            },
        ),
    ]
