# Generated by Django 5.2.6 on 2026-03-01 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0014_logos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_equipamento',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='OrdemArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='ordens/arquivos/')),
                ('descricao', models.CharField(blank=True, max_length=160)),
                ('incluir_relatorio', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_os_enviados', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='ordens.ordemservico')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
