# Generated by Django 5.2.6 on 2026-03-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0015_alter_ordemservico_tipo_equipamento_ordemarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicopeca',
            name='numeros_taloes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
