# Generated by Django 5.2.6 on 2026-03-02 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0014_normalizar_numero_talao_padrao'),
        ('ordens', '0016_servicopeca_numeros_taloes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemTalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=40)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ordens/taloes/')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('pagamento', 'Pagamento')], default='manual', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taloes_criados', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taloes', to='ordens.ordemservico')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taloes_os', to='caixa.pagamento')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'unique_together': {('ordem', 'numero')},
            },
        ),
    ]
