# Generated by Django 5.2.6 on 2026-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0017_ordemtalao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemtalao',
            name='item_referencia',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='ordemtalao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
