# Generated by Django 5.2.6 on 2026-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0019_servicopeca_tecnico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicopeca',
            name='garantia_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
