# Generated by Django 5.2.6 on 2026-03-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_itemorcamento_tipo_item'),
        ('ordens', '0020_servicopeca_garantia_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicopeca',
            name='item_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_pecas', to='orcamentos.itemorcamento'),
        ),
    ]
