# Generated by Django 5.2.6 on 2026-03-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0022_servicopeca_produto_estoque_and_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='manutencao_preventiva_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Intervalo sugerido para manutencao preventiva futura.', null=True),
        ),
    ]
