# Generated by Django 5.2.6 on 2026-03-17 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0023_ordemservico_manutencao_preventiva_meses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhatrabalho',
            name='tipo_evento',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('sistema', 'Sistema')], default='manual', max_length=12),
        ),
        migrations.AlterField(
            model_name='logos',
            name='tipo_evento',
            field=models.CharField(choices=[('alteracao_status', 'Alteração de status'), ('confirmacao', 'Confirmação'), ('edicao_critica', 'Edição crítica'), ('cancelamento', 'Cancelamento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacaocliente',
            name='tipo',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('pronto', 'Equipamento pronto'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='manutencao_preventiva_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Intervalo sugerido para manutenção preventiva futura.', null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo_usuario': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_confirmacao',
            field=models.CharField(blank=True, choices=[('link', 'Confirmação por link'), ('presencial_assinatura', 'Presencial com assinatura'), ('impresso', 'Impresso')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponível'), ('orcamentado', 'Orçamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Trânsito'), ('fechado', 'Fechado')], default='contactar', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidocompralinha',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponível'), ('orcamentado', 'Orçamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Trânsito'), ('fechado', 'Fechado')], max_length=30),
        ),
    ]
