# Generated by Django 5.2.6 on 2026-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0024_alter_linhatrabalho_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='referencia_parceiro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='linhatrabalho',
            name='status',
            field=models.CharField(choices=[('criada', 'Ordem criada'), ('diagnosticar', 'Diagnosticar'), ('bancada', 'Bancada'), ('reparo', 'Reparo em andamento'), ('pendente_pecas', 'Pendente peças'), ('pendente_cliente', 'Pendente cliente'), ('pendente_marca', 'Pendente marca'), ('orcamentado', 'Orçamentado'), ('transito_outdoor', 'Trânsito outdoor'), ('enviado_parceiro', 'Enviado ao parceiro'), ('pronto_contactado', 'Pronto contactado'), ('devolucao', 'Devolução sem reparação'), ('concluida', 'Concluído')], default='criada', max_length=30),
        ),
    ]
