# Generated by Django 5.2.6 on 2026-04-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0027_renomear_label_pronto_contactado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicopeca',
            name='comissionavel',
            field=models.BooleanField(default=True),
        ),
    ]
