# Generated by Django 5.2.6 on 2026-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0028_servicopeca_comissionavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='assinatura_entrada_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ordens/assinaturas/entrada/'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='assinatura_saida_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ordens/assinaturas/saida/'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_assinatura_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_assinatura_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
