# Generated by Django 5.2.6 on 2026-05-05 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0030_restaurar_orcamentado_e_guias_expedicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhatrabalho',
            name='status',
            field=models.CharField(choices=[('criada', 'Ordem criada'), ('diagnosticar', 'Diagnosticar'), ('em_andamento', 'Bancada'), ('pendente_pecas', 'Pendente peÃ§as'), ('pendente_cliente', 'Pendente cliente'), ('pendente_marca', 'Pendente marca'), ('orcamentado', 'OrÃ§amentado'), ('autorizado', 'Autorizado'), ('pronto_envio_parceiro', 'Pronto para envio parceiro'), ('transito_outdoor', 'TrÃ¢nsito outdoor'), ('enviado_parceiro', 'Enviado ao parceiro'), ('pronto_contactado', 'Pronto contactado'), ('devolucao', 'DevoluÃ§Ã£o sem reparaÃ§Ã£o'), ('concluida', 'ConcluÃ\xaddo')], default='criada', max_length=30),
        ),
        migrations.AlterField(
            model_name='linhatrabalho',
            name='tipo_evento',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'AutomÃ¡tico'), ('sistema', 'Sistema')], default='manual', max_length=12),
        ),
        migrations.AlterField(
            model_name='linhatrabalho',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UsuÃ¡rio responsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='tipo_evento',
            field=models.CharField(choices=[('alteracao_status', 'AlteraÃ§Ã£o de status'), ('confirmacao', 'ConfirmaÃ§Ã£o'), ('edicao_critica', 'EdiÃ§Ã£o crÃ\xadtica'), ('cancelamento', 'Cancelamento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacaocliente',
            name='tipo',
            field=models.CharField(choices=[('orcamento', 'OrÃ§amento'), ('pronto', 'Equipamento pronto'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='manutencao_preventiva_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Intervalo sugerido para manutenÃ§Ã£o preventiva futura.', null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('diagnosticar', 'Diagnosticar'), ('em_andamento', 'Bancada'), ('pendente_tecnico', 'Pendente TÃ©cnico'), ('pendente_cliente', 'Pendente cliente'), ('pendente_marca', 'Pendente Marca'), ('pendente_pecas', 'Pendente PeÃ§as'), ('pendente_orcamento', 'Pendente OrÃ§amento'), ('orcamentado', 'OrÃ§amentado'), ('autorizado', 'Autorizado'), ('pronto_envio_parceiro', 'Pronto para envio parceiro'), ('transito_outdoor', 'TrÃ¢nsito outdoor'), ('enviado_parceiro', 'Enviado ao parceiro'), ('recusado', 'Recusado'), ('devolucao', 'DevoluÃ§Ã£o sem reparaÃ§Ã£o'), ('pronto_contactado', 'Pronto contactado'), ('concluida', 'ConcluÃ\xadda')], default='diagnosticar', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo_usuario': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='TÃ©cnico responsÃ¡vel'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_confirmacao',
            field=models.CharField(blank=True, choices=[('link', 'ConfirmaÃ§Ã£o por link'), ('presencial_assinatura', 'Presencial com assinatura'), ('impresso', 'Impresso')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_reparacao',
            field=models.CharField(blank=True, choices=[('substituicao', 'SubstituiÃ§Ã£o de PeÃ§as'), ('reparacao_sem_pecas', 'ReparaÃ§Ã£o sem PeÃ§as'), ('nada', 'Nada Efetuado'), ('recusado_preco', 'Devolvido - Recusado (PreÃ§o)'), ('recusado_tempo', 'Devolvido - Recusado (Tempo)')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_reparo',
            field=models.CharField(choices=[('Garantia', 'Garantia'), ('Fora de Garantia', 'Fora de Garantia'), ('Garantia de serviÃ§o', 'Garantia de serviÃ§o')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'IndisponÃ\xadvel'), ('orcamentado', 'OrÃ§amentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'TrÃ¢nsito'), ('fechado', 'Fechado')], default='contactar', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidocompralinha',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'IndisponÃ\xadvel'), ('orcamentado', 'OrÃ§amentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'TrÃ¢nsito'), ('fechado', 'Fechado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servicopeca',
            name='tipo',
            field=models.CharField(choices=[('servico', 'ServiÃ§o'), ('peca', 'PeÃ§a')], max_length=20),
        ),
    ]
