# Generated by Django 5.2.6 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordens", "0031_alter_linhatrabalho_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guiaexpedicaoitem",
            name="status_retorno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diagnosticar", "Diagnosticar"),
                    ("em_andamento", "Bancada"),
                    ("pendente_tecnico", "Pendente Tecnico"),
                    ("pendente_cliente", "Pendente cliente"),
                    ("pendente_marca", "Pendente Marca"),
                    ("pendente_pecas", "Pendente Pecas"),
                    ("pendente_orcamento", "Pendente Orcamento"),
                    ("orcamentado", "Orcamentado"),
                    ("autorizado", "Autorizado"),
                    ("pronto_envio_parceiro", "Pronto para envio parceiro"),
                    ("transito_outdoor", "Transito outdoor"),
                    ("enviado_parceiro", "Enviado ao parceiro"),
                    ("recepcionado", "Recepcionado"),
                    ("recusado", "Recusado"),
                    ("devolucao", "Devolucao sem reparacao"),
                    ("pronto_contactado", "Pronto contactado"),
                    ("concluida", "Concluida"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linhatrabalho",
            name="status",
            field=models.CharField(
                choices=[
                    ("criada", "Ordem criada"),
                    ("diagnosticar", "Diagnosticar"),
                    ("em_andamento", "Bancada"),
                    ("pendente_pecas", "Pendente pecas"),
                    ("pendente_cliente", "Pendente cliente"),
                    ("pendente_marca", "Pendente marca"),
                    ("orcamentado", "Orcamentado"),
                    ("autorizado", "Autorizado"),
                    ("pronto_envio_parceiro", "Pronto para envio parceiro"),
                    ("transito_outdoor", "Transito outdoor"),
                    ("enviado_parceiro", "Enviado ao parceiro"),
                    ("recepcionado", "Recepcionado"),
                    ("pronto_contactado", "Pronto contactado"),
                    ("devolucao", "Devolucao sem reparacao"),
                    ("concluida", "Concluido"),
                ],
                default="criada",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("diagnosticar", "Diagnosticar"),
                    ("em_andamento", "Bancada"),
                    ("pendente_tecnico", "Pendente Tecnico"),
                    ("pendente_cliente", "Pendente cliente"),
                    ("pendente_marca", "Pendente Marca"),
                    ("pendente_pecas", "Pendente Pecas"),
                    ("pendente_orcamento", "Pendente Orcamento"),
                    ("orcamentado", "Orcamentado"),
                    ("autorizado", "Autorizado"),
                    ("pronto_envio_parceiro", "Pronto para envio parceiro"),
                    ("transito_outdoor", "Transito outdoor"),
                    ("enviado_parceiro", "Enviado ao parceiro"),
                    ("recepcionado", "Recepcionado"),
                    ("recusado", "Recusado"),
                    ("devolucao", "Devolucao sem reparacao"),
                    ("pronto_contactado", "Pronto contactado"),
                    ("concluida", "Concluida"),
                ],
                default="diagnosticar",
                max_length=30,
            ),
        ),
    ]
