# Generated by Django 5.2.6 on 2026-05-07 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0032_status_recepcionado_expedicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaexpedicaoitem',
            name='status_retorno',
            field=models.CharField(blank=True, choices=[('diagnosticar', 'Diagnosticar'), ('em_andamento', 'Bancada'), ('pendente_pecas', 'Pendente peças'), ('pendente_orcamento', 'Pendente orçamento'), ('orcamentado', 'Orçamentado'), ('autorizado', 'Autorizado'), ('pronto_envio_parceiro', 'Pronto para envio parceiro'), ('recepcionado', 'Recepcionado')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linhatrabalho',
            name='status',
            field=models.CharField(choices=[('criada', 'Ordem criada'), ('diagnosticar', 'Diagnosticar'), ('em_andamento', 'Bancada'), ('pendente_pecas', 'Pendente peças'), ('pendente_cliente', 'Pendente cliente'), ('pendente_marca', 'Pendente marca'), ('orcamentado', 'Orçamentado'), ('autorizado', 'Autorizado'), ('pronto_envio_parceiro', 'Pronto para envio parceiro'), ('transito_outdoor', 'Trânsito outdoor'), ('enviado_parceiro', 'Enviado ao parceiro'), ('recepcionado', 'Recepcionado'), ('pronto_contactado', 'Pronto contactado'), ('devolucao', 'Devolução sem reparação'), ('concluida', 'Concluído')], default='criada', max_length=30),
        ),
        migrations.AlterField(
            model_name='linhatrabalho',
            name='tipo_evento',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('sistema', 'Sistema')], default='manual', max_length=12),
        ),
        migrations.AlterField(
            model_name='linhatrabalho',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='tipo_evento',
            field=models.CharField(choices=[('alteracao_status', 'Alteração de status'), ('confirmacao', 'Confirmação'), ('edicao_critica', 'Edição crítica'), ('cancelamento', 'Cancelamento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacaocliente',
            name='tipo',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('pronto', 'Equipamento pronto'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('diagnosticar', 'Diagnosticar'), ('em_andamento', 'Bancada'), ('pendente_tecnico', 'Pendente Técnico'), ('pendente_cliente', 'Pendente cliente'), ('pendente_marca', 'Pendente Marca'), ('pendente_pecas', 'Pendente Peças'), ('pendente_orcamento', 'Pendente Orçamento'), ('orcamentado', 'Orçamentado'), ('autorizado', 'Autorizado'), ('pronto_envio_parceiro', 'Pronto para envio parceiro'), ('transito_outdoor', 'Trânsito outdoor'), ('enviado_parceiro', 'Enviado ao parceiro'), ('recepcionado', 'Recepcionado'), ('recusado', 'Recusado'), ('devolucao', 'Devolução sem reparação'), ('pronto_contactado', 'Pronto contactado'), ('concluida', 'Concluída')], default='diagnosticar', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_reparacao',
            field=models.CharField(blank=True, choices=[('substituicao', 'Substituição de Peças'), ('reparacao_sem_pecas', 'Reparação sem Peças'), ('nada', 'Nada Efetuado'), ('recusado_preco', 'Devolvido - Recusado (Preço)'), ('recusado_tempo', 'Devolvido - Recusado (Tempo)')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_reparo',
            field=models.CharField(choices=[('Garantia', 'Garantia'), ('Fora de Garantia', 'Fora de Garantia'), ('Garantia de serviço', 'Garantia de serviço')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponível'), ('orcamentado', 'Orçamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Trânsito'), ('fechado', 'Fechado')], default='contactar', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidocompralinha',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponível'), ('orcamentado', 'Orçamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado', 'Recepcionado'), ('transito', 'Trânsito'), ('fechado', 'Fechado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servicopeca',
            name='tipo',
            field=models.CharField(choices=[('servico', 'Serviço'), ('peca', 'Peça')], max_length=20),
        ),
    ]
