# Generated by Django 5.2.6 on 2026-05-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0049_configuracaoauditoria'),
        ('ordens', '0033_alter_guiaexpedicaoitem_status_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='configuracoes.empresa'),
        ),
    ]
