# Generated by Django 5.2.6 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordens", "0034_ordemservico_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="garantia_classificacao_retorno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mesmo_defeito", "Mesmo defeito"),
                    ("novo_defeito", "Novo defeito"),
                    ("mau_uso", "Mau uso"),
                    ("garantia_peca", "Garantia de peça"),
                    ("garantia_mao_obra", "Garantia de mão de obra"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="garantia_reincidencia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="ordem_origem_garantia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retornos_garantia",
                to="ordens.ordemservico",
            ),
        ),
    ]
