# Generated by Django 5.2.6 on 2026-05-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0035_ordemservico_garantia_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaexpedicaoparceiro',
            name='parceiro_nome',
            field=models.CharField(max_length=255),
        ),
    ]
