# Generated by Django 5.2.6 on 2026-05-17 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0037_alter_guiaexpedicaoparceiro_parceiro_nome_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='manutencao_preventiva_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Intervalo sugerido para manutenção preventiva futura.', null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo_usuario': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_confirmacao',
            field=models.CharField(blank=True, choices=[('link', 'Confirmação por link'), ('presencial_assinatura', 'Presencial com assinatura'), ('impresso', 'Impresso')], max_length=30, null=True),
        ),
    ]
