# Generated by Django 5.2.6 on 2026-05-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_produto_empresa'),
        ('ordens', '0038_alter_ordemservico_manutencao_preventiva_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicopeca',
            name='ponto_operacional_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_os_reserva', to='estoque.pontooperacional'),
        ),
    ]
