# Generated by Django 5.2.6 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordens", "0039_servicopeca_ponto_operacional_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="tipo_reparo",
            field=models.CharField(
                choices=[
                    ("Garantia", "Garantia"),
                    ("Fora de Garantia", "Fora de Garantia"),
                    ("Garantia de serviço", "Garantia de serviço"),
                    ("Encomenda", "Encomenda"),
                ],
                max_length=20,
            ),
        ),
    ]
