# Generated by Django 5.2.6 on 2026-07-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0063_configuracaosistema_enviar_whatsapp_abertura_os_and_more'),
        ('ordens', '0040_alter_ordemservico_tipo_reparo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_conferencia', 'Em conferência'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('filtro_local_armazenamento', models.CharField(blank=True, max_length=200)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_ordens', to='configuracoes.empresa')),
                ('usuario_abertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_ordens_abertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_ordens_fechadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacaoOrdemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os_snapshot', models.CharField(max_length=20)),
                ('cliente_snapshot', models.CharField(blank=True, max_length=160)),
                ('tipo_equipamento_snapshot', models.CharField(blank=True, max_length=80)),
                ('modelo_snapshot', models.CharField(blank=True, max_length=120)),
                ('marca_snapshot', models.CharField(blank=True, max_length=120)),
                ('local_armazenamento_snapshot', models.CharField(blank=True, max_length=200)),
                ('status_snapshot', models.CharField(blank=True, max_length=40)),
                ('data_entrada_snapshot', models.DateTimeField(blank=True, null=True)),
                ('data_pronto_snapshot', models.DateTimeField(blank=True, null=True)),
                ('dias_em_aberto_snapshot', models.PositiveIntegerField(default=0)),
                ('valor_parado_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('conferido', 'Confere'), ('divergencia', 'Divergência')], default='pendente', max_length=20)),
                ('motivo_divergencia', models.CharField(blank=True, choices=[('', 'Sem motivo'), ('nao_localizado', 'Não localizado'), ('local_divergente', 'Local divergente'), ('status_divergente', 'Status divergente'), ('equipamento_extra', 'Equipamento extra'), ('dados_divergentes', 'Dados divergentes'), ('outro', 'Outro')], max_length=40)),
                ('observacao', models.CharField(blank=True, max_length=240)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens.conciliacaoordem')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_conciliacao_conferidos', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_conciliacao', to='ordens.ordemservico')),
            ],
            options={
                'ordering': ['local_armazenamento_snapshot', 'numero_os_snapshot'],
                'constraints': [models.UniqueConstraint(fields=('conciliacao', 'ordem_servico'), name='uniq_conciliacao_ordem_item')],
            },
        ),
    ]
