# Generated by Django 5.2.6 on 2026-08-11 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0089_configuracaosistema_pdf_relatorio_modo_resumido'),
        ('estoque', '0056_pre_cadastro_produto_xml'),
        ('orcamentos', '0009_itemorcamento_custo_estimado_unitario_and_more'),
        ('ordens', '0043_alter_ordemservico_numero_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='motivo_sem_cobranca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='resultado_financeiro',
            field=models.CharField(choices=[('cobravel', 'Cobrável'), ('cortesia', 'Cortesia'), ('garantia_servico', 'Garantia de serviço'), ('sem_reparo', 'Sem reparo'), ('cancelada', 'Cancelada'), ('uso_interno', 'Uso interno')], db_index=True, default='cobravel', max_length=24),
        ),
        migrations.CreateModel(
            name='CustoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peca', 'Peça'), ('componente', 'Componente'), ('insumo', 'Insumo'), ('consumivel', 'Consumível'), ('terceiro', 'Serviço de terceiro'), ('frete', 'Frete'), ('outro', 'Outro')], default='insumo', max_length=20)),
                ('origem', models.CharField(choices=[('estoque', 'Estoque'), ('compra_especifica', 'Compra específica'), ('despesa_paga', 'Despesa paga'), ('manual', 'Insumo/material já disponível'), ('ajuste', 'Ajuste autorizado')], default='manual', max_length=24)),
                ('descricao', models.CharField(max_length=180)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unidade', models.CharField(default='UN', max_length=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_competencia', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=160)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('observacao_interna', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_estorno', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_os_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_ordens_servico', to='configuracoes.empresa')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_os_estornados', to=settings.AUTH_USER_MODEL)),
                ('item_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_reais', to='orcamentos.itemorcamento')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_internos', to='ordens.ordemservico')),
                ('produto_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_ordens_servico', to='estoque.produto')),
                ('servico_peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_internos', to='ordens.servicopeca')),
            ],
            options={
                'ordering': ['-data_competencia', '-id'],
                'indexes': [models.Index(fields=['empresa', 'ordem', 'data_competencia'], name='ordens_cust_empresa_e477cc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='custo_os_quantidade_positiva'), models.CheckConstraint(condition=models.Q(('custo_unitario__gte', 0)), name='custo_os_unitario_nao_negativo')],
            },
        ),
    ]
