# Generated by Django 5.2.6 on 2026-08-11 23:51

import django.db.models.deletion
import re
from django.db import migrations, models


def vincular_consumos_historicos(apps, schema_editor):
    CustoOrdemServico = apps.get_model("ordens", "CustoOrdemServico")
    OrdemServico = apps.get_model("ordens", "OrdemServico")
    ServicoPeca = apps.get_model("ordens", "ServicoPeca")
    ReservaEstoque = apps.get_model("estoque", "ReservaEstoque")
    MovimentacaoEstoque = apps.get_model("estoque", "MovimentacaoEstoque")

    movimentos = MovimentacaoEstoque.objects.filter(tipo="consumo_os").select_related(
        "produto", "usuario"
    )
    for movimento in movimentos.iterator():
        if CustoOrdemServico.objects.filter(movimentacao_estoque_id=movimento.pk).exists():
            continue

        ordem = None
        servico = None
        if movimento.origem_tipo == "ordem_servico" and movimento.origem_referencia:
            ordens = OrdemServico.objects.filter(numero_os=movimento.origem_referencia)
            empresa_produto_id = getattr(movimento.produto, "empresa_id", None)
            if empresa_produto_id:
                ordens = ordens.filter(empresa_id=empresa_produto_id)
            ordem = ordens.order_by("-id").first()
            item_match = re.search(r"item\s+(\d+)\s*$", movimento.observacao or "", re.IGNORECASE)
            if ordem and item_match:
                servico = ServicoPeca.objects.filter(
                    pk=int(item_match.group(1)),
                    ordem_id=ordem.pk,
                ).first()
        elif movimento.origem_tipo == "reserva" and movimento.origem_referencia:
            reserva = ReservaEstoque.objects.filter(
                codigo_reserva=movimento.origem_referencia,
                ordem_servico_id__isnull=False,
            ).first()
            ordem = OrdemServico.objects.filter(pk=getattr(reserva, "ordem_servico_id", None)).first()

        if not ordem or not ordem.empresa_id:
            continue

        estorno = MovimentacaoEstoque.objects.filter(
            movimento_estornado_id=movimento.pk
        ).order_by("criado_em", "id").first()
        CustoOrdemServico.objects.create(
            empresa_id=ordem.empresa_id,
            ordem_id=ordem.pk,
            servico_peca_id=getattr(servico, "pk", None),
            item_orcamento_id=getattr(servico, "item_orcamento_id", None),
            produto_estoque_id=movimento.produto_id,
            movimentacao_estoque_id=movimento.pk,
            tipo="peca",
            origem="estoque",
            descricao=(getattr(servico, "nome", "") or movimento.produto.nome)[:180],
            quantidade=abs(movimento.quantidade or 0),
            unidade="UN",
            custo_unitario=movimento.valor_unitario_custo or 0,
            data_competencia=movimento.criado_em.date(),
            documento_referencia=str(ordem.numero_os)[:100],
            observacao_interna="Custo recuperado de uma baixa histórica de estoque.",
            criado_por_id=movimento.usuario_id,
            estornado_em=getattr(estorno, "criado_em", None),
            estornado_por_id=getattr(estorno, "usuario_id", None),
            motivo_estorno="Baixa histórica devolvida ao estoque." if estorno else "",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0050_lancamentocaixa_conta_bancaria_and_more'),
        ('estoque', '0056_pre_cadastro_produto_xml'),
        ('ordens', '0044_ordemservico_motivo_sem_cobranca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoordemservico',
            name='lancamento_caixa',
            field=models.ForeignKey(blank=True, help_text='Saída financeira que pagou este custo, quando aplicável.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custos_ordens_servico', to='caixa.lancamentocaixa'),
        ),
        migrations.AddField(
            model_name='custoordemservico',
            name='movimentacao_estoque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custo_ordem_servico', to='estoque.movimentacaoestoque'),
        ),
        migrations.RunPython(vincular_consumos_historicos, migrations.RunPython.noop),
    ]
