# Generated by Django 5.2.6 on 2026-08-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0051_alter_pagamentocontapagar_options_and_more'),
        ('ordens', '0045_custoordemservico_lancamento_caixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoordemservico',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, help_text='Obrigação que originou este custo, quando aplicável.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custos_ordens_servico', to='caixa.contapagar'),
        ),
    ]
