# Generated by Django 5.2.6 on 2026-08-12 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preencher_empresa_pedidos_existentes(apps, schema_editor):
    PedidoCompra = apps.get_model("ordens", "PedidoCompra")
    for pedido in PedidoCompra.objects.select_related("ordem").filter(empresa__isnull=True).iterator():
        PedidoCompra.objects.filter(pk=pedido.pk).update(empresa_id=pedido.ordem.empresa_id)


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0052_contapagar_natureza_economica'),
        ('configuracoes', '0089_configuracaosistema_pdf_relatorio_modo_resumido'),
        ('estoque', '0056_pre_cadastro_produto_xml'),
        ('orcamentos', '0009_itemorcamento_custo_estimado_unitario_and_more'),
        ('ordens', '0046_custoordemservico_conta_pagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_os', to='caixa.contapagar'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='custo_estimado_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='data_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_os', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='fornecedor_nome',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='item_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='orcamentos.itemorcamento'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='produto_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_os', to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='quantidade_solicitada',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.RunPython(preencher_empresa_pedidos_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponível'), ('orcamentado', 'Orçamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado_parcial', 'Recepcionado parcialmente'), ('recepcionado', 'Recepcionado'), ('transito', 'Trânsito'), ('fechado', 'Fechado')], default='contactar', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidocompralinha',
            name='status',
            field=models.CharField(choices=[('contactar', 'Contactar'), ('indisponivel', 'Indisponível'), ('orcamentado', 'Orçamentado'), ('pedido_incompleto', 'Pedido incompleto'), ('pendente_marca', 'Pendente marca'), ('pendente_cliente', 'Pendente cliente'), ('pre_pagamento', 'Pre-pagamento'), ('recepcionado_parcial', 'Recepcionado parcialmente'), ('recepcionado', 'Recepcionado'), ('transito', 'Trânsito'), ('fechado', 'Fechado')], max_length=30),
        ),
        migrations.CreateModel(
            name='RecebimentoPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('destino', models.CharField(choices=[('uso_os', 'Uso direto na OS'), ('estoque', 'Entrada no estoque')], max_length=12)),
                ('data_competencia', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('chave_idempotencia', models.CharField(max_length=160, unique=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_estorno', models.TextField(blank=True)),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_pedidos_os', to='caixa.contapagar')),
                ('custo_os', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimento_pedido', to='ordens.custoordemservico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_pedidos_os', to='configuracoes.empresa')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_pedidos_os_estornados', to=settings.AUTH_USER_MODEL)),
                ('movimentacao_estoque', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimento_pedido_os', to='estoque.movimentacaoestoque')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='ordens.pedidocompra')),
                ('produto_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_pedidos_os', to='estoque.produto')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_pedidos_os', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recebido_em', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='receb_pedido_os_qtd_positiva'), models.CheckConstraint(condition=models.Q(('custo_unitario__gte', 0)), name='receb_pedido_os_custo_nao_negativo')],
            },
        ),
    ]
