from reportlab.lib import colors


def resolve_layout_preset(config, default="clean"):
    preset = (getattr(config, "layout_documentos_preset", "") or default).strip().lower()
    # Preset "tecnico" foi descontinuado; manter fallback transparente.
    if preset == "tecnico":
        return "clean"
    return preset


def resolve_color_mode(config, default="colorido"):
    return (getattr(config, "layout_documentos_cor", "") or default).strip().lower()


def _color_to_grayscale(value):
    try:
        red = float(value.red)
        green = float(value.green)
        blue = float(value.blue)
    except Exception:
        return value
    luminance = (0.299 * red) + (0.587 * green) + (0.114 * blue)
    return colors.Color(luminance, luminance, luminance)


def _apply_color_mode(theme, config):
    if resolve_color_mode(config) != "pb":
        return theme
    converted = {}
    for key, value in theme.items():
        converted[key] = _color_to_grayscale(value)
    return converted


def get_document_theme(config):
    preset = resolve_layout_preset(config)
    themes = {
        "classico": {
            "title_color": colors.HexColor("#1f2d3d"),
            "meta_color": colors.HexColor("#555555"),
            "section_bg": colors.HexColor("#eef2f7"),
            "section_line": colors.HexColor("#cbd5e1"),
            "section_text": colors.HexColor("#1f3a5f"),
            "table_bg": colors.HexColor("#f8fafc"),
            "row_alt": colors.white,
            "hero_bg": colors.HexColor("#f1f5f9"),
            "hero_text": colors.HexColor("#1f2d3d"),
            "hero_value": colors.HexColor("#0f172a"),
            "badge_bg": colors.HexColor("#1f3a5f"),
            "badge_text": colors.white,
        },
        "clean": {
            "title_color": colors.HexColor("#1f2d3d"),
            "meta_color": colors.HexColor("#4b5563"),
            "section_bg": colors.HexColor("#f3f6fa"),
            "section_line": colors.HexColor("#cbd5e1"),
            "section_text": colors.HexColor("#1f3a5f"),
            "table_bg": colors.HexColor("#f8fafc"),
            "row_alt": colors.white,
            "hero_bg": colors.HexColor("#f8fafc"),
            "hero_text": colors.HexColor("#374151"),
            "hero_value": colors.HexColor("#111827"),
            "badge_bg": colors.HexColor("#1f3a5f"),
            "badge_text": colors.white,
        },
        "compacto": {
            "title_color": colors.HexColor("#1f2937"),
            "meta_color": colors.HexColor("#4b5563"),
            "section_bg": colors.HexColor("#eef2f7"),
            "section_line": colors.HexColor("#cbd5e1"),
            "section_text": colors.HexColor("#1f2937"),
            "table_bg": colors.HexColor("#f8fafc"),
            "row_alt": colors.white,
            "hero_bg": colors.HexColor("#eef2f7"),
            "hero_text": colors.HexColor("#374151"),
            "hero_value": colors.HexColor("#111827"),
            "badge_bg": colors.HexColor("#1f2937"),
            "badge_text": colors.white,
        },
        "executivo": {
            "title_color": colors.HexColor("#0f172a"),
            "meta_color": colors.HexColor("#334155"),
            "section_bg": colors.HexColor("#e2e8f0"),
            "section_line": colors.HexColor("#94a3b8"),
            "section_text": colors.HexColor("#0f172a"),
            "table_bg": colors.HexColor("#f1f5f9"),
            "row_alt": colors.white,
            "hero_bg": colors.HexColor("#0f172a"),
            "hero_text": colors.HexColor("#cbd5e1"),
            "hero_value": colors.white,
            "badge_bg": colors.HexColor("#1e293b"),
            "badge_text": colors.white,
        },
    }
    return _apply_color_mode(themes.get(preset, themes["clean"]), config)


def get_document_profile(config):
    preset = resolve_layout_preset(config)
    base = {
        "pdf_title_pt": 15.0,
        "pdf_meta_pt": 8.5,
        "pdf_label_pt": 8.5,
        "pdf_value_pt": 9.0,
        "pdf_section_pt": 10.5,
        "pdf_text_pt": 9.0,
        "pdf_header_logo_w_cm": 5.6,
        "pdf_header_logo_h_cm": 2.8,
        "pdf_header_logo_col_cm": 6.0,
        "pdf_label_col_cm": 4.1,
        "pdf_header_gap_cm": 0.4,
        "pdf_block_gap_cm": 0.28,
        "pdf_section_pad_h": 8,
        "pdf_section_pad_v": 4,
        "pdf_cell_pad_h": 6,
        "pdf_cell_pad_v": 4,
        "print_title_pt": 11.0,
        "print_small_pt": 8.2,
        "print_label_pt": 8.2,
        "print_section_pt": 8.6,
        "print_logo_w_cm": 4.6,
        "print_logo_h_cm": 2.3,
        "print_logo_col_cm": 5.0,
        "print_section_pad_h": 7,
        "print_section_pad_v": 4,
        "print_cell_pad_h": 5,
        "print_cell_pad_v": 3,
        "rt_title_pt": 14.0,
        "rt_meta_pt": 8.0,
        "rt_label_pt": 8.5,
        "rt_value_pt": 9.0,
        "rt_section_pt": 10.0,
        "rt_text_pt": 9.0,
        "rt_logo_w_cm": 4.8,
        "rt_logo_h_cm": 2.4,
        "rt_logo_col_cm": 5.4,
        "rt_label_col_cm": 4.1,
        "rt_header_gap_cm": 0.22,
        "rt_block_gap_cm": 0.20,
        "rt_section_pad_h": 8,
        "rt_section_pad_v": 4,
        "rt_cell_pad_h": 6,
        "rt_cell_pad_v": 4,
        "orc_title_pt": 14.0,
        "orc_meta_pt": 8.0,
        "orc_label_pt": 8.5,
        "orc_value_pt": 9.0,
        "orc_section_pt": 10.0,
        "orc_text_pt": 9.0,
        "orc_logo_w_cm": 3.0,
        "orc_logo_h_cm": 1.8,
        "orc_logo_col_cm": 3.1,
        "orc_label_col_cm": 4.1,
        "orc_header_gap_cm": 0.22,
        "orc_block_gap_cm": 0.20,
        "orc_section_pad_h": 8,
        "orc_section_pad_v": 4,
        "orc_cell_pad_h": 6,
        "orc_cell_pad_v": 4,
        "orc_item_desc_cm": 8.5,
        "orc_item_qtd_cm": 1.9,
        "orc_item_unit_cm": 2.7,
        "orc_item_total_cm": 2.7,
        "orc_total_col_cm": 4.5,
    }
    overrides = {
        "compacto": {
            "pdf_title_pt": 13.8,
            "pdf_meta_pt": 7.9,
            "pdf_label_pt": 8.0,
            "pdf_value_pt": 8.5,
            "pdf_section_pt": 9.6,
            "pdf_text_pt": 8.5,
            "pdf_header_logo_w_cm": 4.9,
            "pdf_header_logo_h_cm": 2.3,
            "pdf_header_logo_col_cm": 5.3,
            "pdf_label_col_cm": 3.8,
            "pdf_header_gap_cm": 0.28,
            "pdf_block_gap_cm": 0.20,
            "pdf_section_pad_h": 7,
            "pdf_section_pad_v": 3,
            "pdf_cell_pad_h": 5,
            "pdf_cell_pad_v": 3,
            "print_title_pt": 10.2,
            "print_small_pt": 7.8,
            "print_label_pt": 7.8,
            "print_section_pt": 8.1,
            "print_logo_w_cm": 4.2,
            "print_logo_h_cm": 2.0,
            "print_logo_col_cm": 4.6,
            "print_section_pad_h": 6,
            "print_section_pad_v": 3,
            "print_cell_pad_h": 4,
            "print_cell_pad_v": 2.5,
            "rt_title_pt": 13.0,
            "rt_meta_pt": 7.6,
            "rt_label_pt": 8.0,
            "rt_value_pt": 8.5,
            "rt_section_pt": 9.5,
            "rt_text_pt": 8.5,
            "rt_logo_w_cm": 4.3,
            "rt_logo_h_cm": 2.0,
            "rt_logo_col_cm": 4.9,
            "rt_label_col_cm": 3.9,
            "rt_header_gap_cm": 0.16,
            "rt_block_gap_cm": 0.16,
            "rt_section_pad_h": 7,
            "rt_section_pad_v": 3,
            "rt_cell_pad_h": 5,
            "rt_cell_pad_v": 3,
            "orc_title_pt": 13.0,
            "orc_meta_pt": 7.6,
            "orc_label_pt": 8.0,
            "orc_value_pt": 8.5,
            "orc_section_pt": 9.4,
            "orc_text_pt": 8.6,
            "orc_logo_w_cm": 2.7,
            "orc_logo_h_cm": 1.5,
            "orc_logo_col_cm": 2.8,
            "orc_label_col_cm": 3.8,
            "orc_header_gap_cm": 0.16,
            "orc_block_gap_cm": 0.16,
            "orc_section_pad_h": 7,
            "orc_section_pad_v": 3,
            "orc_cell_pad_h": 5,
            "orc_cell_pad_v": 3,
            "orc_item_desc_cm": 8.2,
            "orc_item_qtd_cm": 1.8,
            "orc_item_unit_cm": 2.6,
            "orc_item_total_cm": 2.6,
            "orc_total_col_cm": 4.2,
        },
        "executivo": {
            "pdf_title_pt": 16.0,
            "pdf_meta_pt": 8.8,
            "pdf_label_pt": 8.8,
            "pdf_value_pt": 9.2,
            "pdf_section_pt": 10.8,
            "pdf_text_pt": 9.2,
            "pdf_header_logo_w_cm": 6.1,
            "pdf_header_logo_h_cm": 3.0,
            "pdf_header_logo_col_cm": 6.4,
            "pdf_label_col_cm": 4.4,
            "pdf_header_gap_cm": 0.46,
            "pdf_block_gap_cm": 0.32,
            "pdf_section_pad_h": 9,
            "pdf_section_pad_v": 5,
            "pdf_cell_pad_h": 7,
            "pdf_cell_pad_v": 5,
            "print_title_pt": 11.4,
            "print_small_pt": 8.4,
            "print_label_pt": 8.4,
            "print_section_pt": 8.9,
            "print_logo_w_cm": 4.8,
            "print_logo_h_cm": 2.4,
            "print_logo_col_cm": 5.2,
            "print_section_pad_h": 8,
            "print_section_pad_v": 4.5,
            "print_cell_pad_h": 6,
            "print_cell_pad_v": 3.5,
            "rt_title_pt": 14.8,
            "rt_meta_pt": 8.2,
            "rt_label_pt": 8.7,
            "rt_value_pt": 9.2,
            "rt_section_pt": 10.3,
            "rt_text_pt": 9.2,
            "rt_logo_w_cm": 5.1,
            "rt_logo_h_cm": 2.5,
            "rt_logo_col_cm": 5.7,
            "rt_label_col_cm": 4.3,
            "rt_header_gap_cm": 0.26,
            "rt_block_gap_cm": 0.24,
            "rt_section_pad_h": 9,
            "rt_section_pad_v": 5,
            "rt_cell_pad_h": 7,
            "rt_cell_pad_v": 5,
            "orc_title_pt": 14.8,
            "orc_meta_pt": 8.2,
            "orc_label_pt": 8.8,
            "orc_value_pt": 9.2,
            "orc_section_pt": 10.3,
            "orc_text_pt": 9.2,
            "orc_logo_w_cm": 3.2,
            "orc_logo_h_cm": 1.9,
            "orc_logo_col_cm": 3.3,
            "orc_label_col_cm": 4.3,
            "orc_header_gap_cm": 0.26,
            "orc_block_gap_cm": 0.24,
            "orc_section_pad_h": 9,
            "orc_section_pad_v": 5,
            "orc_cell_pad_h": 7,
            "orc_cell_pad_v": 5,
            "orc_item_desc_cm": 8.8,
            "orc_item_qtd_cm": 1.9,
            "orc_item_unit_cm": 2.7,
            "orc_item_total_cm": 2.7,
            "orc_total_col_cm": 4.8,
        },
    }
    base.update(overrides.get(preset, {}))
    return base


__all__ = ["get_document_profile", "get_document_theme", "resolve_color_mode", "resolve_layout_preset"]
