# Generated by Django 5.2.6 on 2026-03-15 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologacao'), ('producao', 'Producao')], default='homologacao', max_length=20)),
                ('modo_integracao', models.CharField(choices=[('direto_ws', 'Direto via Webservice'), ('api_terceiro', 'API terceira')], default='direto_ws', max_length=20)),
                ('fornecedor_api', models.CharField(blank=True, max_length=120)),
                ('certificado_a1', models.FileField(blank=True, null=True, upload_to='fiscal/certificados/')),
                ('senha_certificado', models.CharField(blank=True, max_length=120)),
                ('cnpj_emitente', models.CharField(blank=True, max_length=18)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30)),
                ('serie_nfe', models.PositiveIntegerField(default=1)),
                ('serie_nfce', models.PositiveIntegerField(default=1)),
                ('proximo_numero_nfe', models.PositiveIntegerField(default=1)),
                ('proximo_numero_nfce', models.PositiveIntegerField(default=1)),
                ('nfse_habilitada', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao fiscal',
                'verbose_name_plural': 'Configuracoes fiscais',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NFE', 'NF-e'), ('NFCE', 'NFC-e'), ('NFSE', 'NFS-e')], max_length=10)),
                ('origem', models.CharField(choices=[('OS', 'Ordem de Servico'), ('VENDA_BALCAO', 'Venda balcao'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('origem_referencia', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('fila', 'Fila'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('serie', models.PositiveIntegerField(default=1)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=64)),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=80)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('xml_envio', models.TextField(blank=True)),
                ('xml_retorno', models.TextField(blank=True)),
                ('mensagem_retorno', models.TextField(blank=True)),
                ('emitido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscais_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
