# Generated by Django 5.2.6 on 2026-03-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaofiscal',
            options={'verbose_name': 'Configuração fiscal', 'verbose_name_plural': 'Configurações fiscais'},
        ),
        migrations.AlterField(
            model_name='configuracaofiscal',
            name='ambiente',
            field=models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='origem',
            field=models.CharField(choices=[('OS', 'Ordem de Serviço'), ('VENDA_BALCAO', 'Venda balcão'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20),
        ),
    ]
