# Generated by Django 5.2.6 on 2026-08-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_regra_classificacao_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regratributaria',
            name='finalidade',
            field=models.CharField(choices=[('revenda', 'Revenda'), ('prestacao', 'Prestação de serviço'), ('industrializacao', 'Industrialização'), ('oferta', 'Oferta/brinde'), ('cedencia', 'Cedência'), ('uso_consumo', 'Uso/consumo'), ('perda', 'Perda'), ('avaria', 'Avaria'), ('vencimento', 'Vencimento'), ('devolucao', 'Devolução')], max_length=20),
        ),
    ]
