# Generated by Django 5.2.6 on 2026-08-06 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0088_fornecedor_comercial_cnpj'),
        ('estoque', '0056_pre_cadastro_produto_xml'),
        ('fiscal', '0008_alter_regratributaria_finalidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado_a1_protegido',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado_cnpj',
            field=models.CharField(blank=True, editable=False, max_length=14),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado_fingerprint_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado_inicio',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado_serial',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado_titular',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado_validade',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='max_nsu',
            field=models.CharField(default='000000000000000', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='proxima_sincronizacao_dfe',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='senha_certificado_protegida',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='ultima_mensagem_dfe',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='ultima_sincronizacao_dfe',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='ultimo_nsu',
            field=models.CharField(default='000000000000000', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='ultimo_status_dfe',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.CreateModel(
            name='ExecucaoSincronizacaoDFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], max_length=20)),
                ('nsu_inicial', models.CharField(max_length=15)),
                ('ultimo_nsu', models.CharField(blank=True, max_length=15)),
                ('max_nsu', models.CharField(blank=True, max_length=15)),
                ('codigo_status', models.CharField(blank=True, max_length=10)),
                ('mensagem_status', models.CharField(blank=True, max_length=300)),
                ('documentos_recebidos', models.PositiveIntegerField(default=0)),
                ('documentos_novos', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('iniciada', 'Iniciada'), ('concluida', 'Concluída'), ('sem_documentos', 'Sem documentos novos'), ('bloqueada', 'Bloqueada pelo autorizador'), ('erro', 'Erro')], default='iniciada', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sincronizacoes_dfe', to='configuracoes.empresa')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizacoes_dfe_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoDistribuicaoDFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsu', models.CharField(max_length=15)),
                ('schema', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('resumo_nfe', 'Resumo de NF-e'), ('nfe_completa', 'NF-e completa'), ('evento', 'Evento'), ('outro', 'Outro documento')], default='outro', max_length=20)),
                ('disponibilidade', models.CharField(choices=[('resumo', 'Somente resumo'), ('xml_completo', 'XML completo'), ('evento', 'Evento'), ('nao_importavel', 'Não importável')], default='nao_importavel', max_length=20)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44)),
                ('numero', models.CharField(blank=True, db_index=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('cnpj_emitente', models.CharField(blank=True, db_index=True, max_length=14)),
                ('nome_emitente', models.CharField(blank=True, max_length=200)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('situacao_nfe', models.CharField(blank=True, max_length=10)),
                ('xml_protegido', models.TextField(blank=True, editable=False)),
                ('xml_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_distribuicao_dfe', to='configuracoes.empresa')),
                ('entrada_mercadoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_dfe_origem', to='estoque.entradamercadoria')),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='fiscal.execucaosincronizacaodfe')),
            ],
            options={
                'ordering': ['-data_emissao', '-id'],
                'indexes': [models.Index(fields=['empresa', 'numero'], name='fiscal_dfe_emp_num_idx'), models.Index(fields=['empresa', 'cnpj_emitente'], name='fiscal_dfe_emp_emit_idx'), models.Index(fields=['empresa', 'disponibilidade'], name='fiscal_dfe_emp_disp_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nsu'), name='fiscal_dfe_empresa_nsu_unico')],
            },
        ),
    ]
