# Generated by Django 5.2.6 on 2026-02-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_categoriafinanceira_pontooperacional_and_more'),
        ('ordens', '0004_ordemservico_codigo_portal_notificacaocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ponto_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixa.pontooperacional')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraComissaoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_servico', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('percentual_peca', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_comissao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_servico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('base_peca', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('considerar_pecas', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('referencia_pagamento', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='ordens.ordemservico')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_tecnico', to=settings.AUTH_USER_MODEL)),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixa.regracomissaotecnico')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'unique_together': {('ordem_servico', 'tecnico', 'considerar_pecas')},
            },
        ),
    ]
