# Generated by Django 5.2.6 on 2026-02-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_despesarecorrente_regracomissaotecnico_and_more'),
        ('estoque', '0003_pontooperacional_alter_movimentacaoestoque_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='ponto_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.pontooperacional'),
        ),
        migrations.AlterField(
            model_name='despesarecorrente',
            name='ponto_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.pontooperacional'),
        ),
    ]
