# Generated by Django 5.2.6 on 2026-02-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_alter_contareceber_ponto_operacional_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PontoOperacional',
        ),
    ]
