# Generated by Django 5.2.6 on 2026-02-21 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_delete_pontooperacional'),
        ('orcamentos', '0002_itemorcamento_tecnico_responsavel'),
        ('ordens', '0005_alter_ordemservico_tecnico_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_pagamento', models.CharField(choices=[('antecipado', 'Antecipado'), ('fechamento', 'No fechamento')], default='fechamento', max_length=20)),
                ('base_calculo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentual_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('referencia_pagamento', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='orcamentos.itemorcamento')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_itens', to='ordens.ordemservico')),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixa.regracomissaotecnico')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_itens_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'unique_together': {('item_orcamento', 'modo_pagamento')},
            },
        ),
    ]
