# Generated by Django 5.2.6 on 2026-02-21 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_comissaoitemorcamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraPremioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('metrica', models.CharField(choices=[('margem_loja', 'Margem da loja'), ('faturamento_loja', 'Faturamento da loja')], default='margem_loja', max_length=30)),
                ('meta_alvo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('publico', models.CharField(choices=[('tecnico', 'Tecnicos'), ('atendente', 'Atendentes'), ('todos_operacionais', 'Todos operacionais')], default='tecnico', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FaixaPremioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_minima', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meta_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premio_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='caixa.regrapremiometa')),
            ],
            options={
                'ordering': ['ordem', 'meta_minima'],
            },
        ),
        migrations.CreateModel(
            name='PremioColaboradorCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('valor_metrica', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentual_atingimento', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('premio_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_competencia', to=settings.AUTH_USER_MODEL)),
                ('faixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios', to='caixa.faixapremiometa')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_competencia', to='caixa.regrapremiometa')),
            ],
            options={
                'ordering': ['-competencia', '-id'],
                'unique_together': {('colaborador', 'regra', 'competencia')},
            },
        ),
    ]
