# Generated by Django 5.2.6 on 2026-02-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0007_regrapremiometa_faixapremiometa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('credito', 'Cartao de Credito'), ('debito', 'Cartao de Debito'), ('garantia_fabricante', 'Garantia Fabricante'), ('loja', 'Custo da Loja')], max_length=30),
        ),
    ]
