# Generated by Django 5.2.6 on 2026-02-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_alter_pagamento_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracomissaotecnico',
            name='comissionar_garantia',
            field=models.BooleanField(default=False),
        ),
    ]
