# Generated by Django 5.2.6 on 2026-02-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0009_regracomissaotecnico_comissionar_garantia'),
        ('configuracoes', '0010_alter_regragarantiamarca_options_and_more'),
        ('ordens', '0006_ordemservico_marca_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_previsto_fabricante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comissao_prevista_tecnica', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status_faturamento', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('referencia_faturamento', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.fornecedorgarantia')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.marcagarantia')),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_garantia', to='ordens.ordemservico')),
                ('regra_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.regragarantiamarca')),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
    ]
