# Generated by Django 5.2.6 on 2026-03-01 17:46

from django.db import migrations, models


def preencher_tipo_origem(apps, schema_editor):
    ContaReceber = apps.get_model("caixa", "ContaReceber")
    ContaReceber.objects.filter(descricao__icontains="Garantia fabricante").update(tipo_origem="garantia_fabricante")
    ContaReceber.objects.filter(tipo_origem="avulso", ordem_servico__isnull=False).update(tipo_origem="cliente_os")


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0010_auditoriagarantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='tipo_origem',
            field=models.CharField(choices=[('cliente_os', 'Cliente OS'), ('garantia_fabricante', 'Garantia Fabricante'), ('avulso', 'Avulso')], db_index=True, default='avulso', max_length=24),
        ),
        migrations.RunPython(preencher_tipo_origem, noop_reverse),
    ]
