# Generated by Django 5.2.6 on 2026-03-02 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_formas_pagamento(apps, schema_editor):
    FormaPagamento = apps.get_model("caixa", "FormaPagamento")
    Pagamento = apps.get_model("caixa", "Pagamento")

    defaults = [
        {"nome": "Dinheiro", "codigo": "dinheiro", "tipo": "avista", "taxa_percentual": 0, "dias_recebimento": 0, "ativa": True},
        {"nome": "PIX", "codigo": "pix", "tipo": "avista", "taxa_percentual": 0, "dias_recebimento": 0, "ativa": True},
        {"nome": "Cartao Credito", "codigo": "cartao_credito", "tipo": "aprazo", "taxa_percentual": 0, "dias_recebimento": 30, "ativa": True},
        {"nome": "Cartao Debito", "codigo": "cartao_debito", "tipo": "avista", "taxa_percentual": 0, "dias_recebimento": 1, "ativa": True},
        {"nome": "Transferencia", "codigo": "transferencia", "tipo": "avista", "taxa_percentual": 0, "dias_recebimento": 0, "ativa": True},
        {"nome": "Garantia Fabricante", "codigo": "garantia_fabricante", "tipo": "aprazo", "taxa_percentual": 0, "dias_recebimento": 30, "ativa": True},
        {"nome": "Custo da Loja", "codigo": "loja", "tipo": "avista", "taxa_percentual": 0, "dias_recebimento": 0, "ativa": True},
    ]
    for row in defaults:
        FormaPagamento.objects.update_or_create(codigo=row["codigo"], defaults=row)

    map_legacy = {
        "credito": "cartao_credito",
        "debito": "cartao_debito",
    }
    for pagamento in Pagamento.objects.all():
        codigo = (pagamento.metodo or "").strip()
        if not codigo:
            continue
        codigo = map_legacy.get(codigo, codigo)
        forma = FormaPagamento.objects.filter(codigo=codigo).first()
        if forma and pagamento.forma_pagamento_id != forma.id:
            pagamento.forma_pagamento_id = forma.id
            pagamento.save(update_fields=["forma_pagamento"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0011_contareceber_tipo_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('fixo', 'Fixo'), ('variavel', 'Variavel')], default='variavel', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('avista', 'A vista'), ('aprazo', 'A prazo')], default='avista', max_length=10)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dias_recebimento', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='caixa',
            name='diferenca_fechamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caixa',
            name='justificativa_diferenca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='valor_contado_fisico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='caixa.centrocusto'),
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('descricao', models.CharField(max_length=220)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='caixa.centrocusto')),
            ],
            options={
                'ordering': ['-vencimento', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='caixa.formapagamento'),
        ),
        migrations.CreateModel(
            name='PagamentoContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('observacao', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_conta_pagar', to='caixa.caixa')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='caixa.contapagar')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_conta_pagar', to='caixa.formapagamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.RunPython(seed_formas_pagamento, noop_reverse),
    ]
