# Generated by Django 5.2.6 on 2026-03-02 12:31

from django.db import migrations, models
from django.utils import timezone


def popular_taloes(apps, schema_editor):
    Pagamento = apps.get_model("caixa", "Pagamento")
    for pagamento in Pagamento.objects.filter(numero_talao__isnull=True).order_by("id"):
        data_ref = pagamento.data or timezone.now()
        pagamento.numero_talao = f"000100{data_ref:%Y%m%d}{pagamento.id:06d}"
        if not pagamento.data_emissao_talao:
            pagamento.data_emissao_talao = data_ref
        pagamento.save(update_fields=["numero_talao", "data_emissao_talao"])


def reverter_taloes(apps, schema_editor):
    Pagamento = apps.get_model("caixa", "Pagamento")
    Pagamento.objects.all().update(numero_talao=None, data_emissao_talao=None)


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_centrocusto_formapagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_emissao_talao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='numero_talao',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(popular_taloes, reverter_taloes),
    ]
