# Generated by Django 5.2.6 on 2026-03-02 12:51

from django.db import migrations
from django.utils import timezone


def normalizar_taloes(apps, schema_editor):
    Pagamento = apps.get_model("caixa", "Pagamento")
    ConfiguracaoSistema = apps.get_model("configuracoes", "ConfiguracaoSistema")

    config = ConfiguracaoSistema.objects.filter(pk=1).first()
    numero_loja = "01"
    if config and getattr(config, "numero_loja_talao", None):
        numero_loja = str(config.numero_loja_talao).zfill(2)[:2]

    for pagamento in Pagamento.objects.all().order_by("id"):
        data_ref = pagamento.data or timezone.now()
        novo_numero = f"00{numero_loja}00{data_ref:%Y%m%d}{pagamento.id:06d}"
        if pagamento.numero_talao != novo_numero or not pagamento.data_emissao_talao:
            pagamento.numero_talao = novo_numero
            if not pagamento.data_emissao_talao:
                pagamento.data_emissao_talao = data_ref
            pagamento.save(update_fields=["numero_talao", "data_emissao_talao"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0013_pagamento_data_emissao_talao_pagamento_numero_talao'),
        ('configuracoes', '0022_configuracaosistema_numero_loja_talao'),
    ]

    operations = [
        migrations.RunPython(normalizar_taloes, noop_reverse),
    ]
