# Generated by Django 5.2.6 on 2026-03-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0014_normalizar_numero_talao_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocaixa',
            name='pagamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamento_caixa', to='caixa.pagamento'),
        ),
    ]
