# Generated by Django 5.2.6 on 2026-03-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0015_lancamentocaixa_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracomissaotecnico',
            name='exigir_pagamento_para_liberar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regracomissaotecnico',
            name='momento_liberacao',
            field=models.CharField(choices=[('entregue_pago', 'Somente apos entrega ao cliente + pagamento'), ('pronto_contactado', 'A partir de pronto contactado (adiantamento)')], default='entregue_pago', max_length=24),
        ),
    ]
