# Generated by Django 5.2.6 on 2026-03-06 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0016_regracomissaotecnico_exigir_pagamento_para_liberar_and_more'),
        ('estoque', '0011_produto_bonus_venda_produto_percentual_comissao_peca_and_more'),
        ('orcamentos', '0003_itemorcamento_tipo_item'),
        ('ordens', '0020_servicopeca_garantia_dias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICO', 'Servico'), ('PECA', 'Peca'), ('BONUS_PRODUTO', 'Bonus por produto'), ('BONUS_RETIRADA', 'Bonus por retirada'), ('BONUS_SERVICO', 'Bonus de servico')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('evento_gerador', models.CharField(default='SERVICO_FINALIZADO', max_length=40)),
                ('status', models.CharField(choices=[('GERADA', 'Gerada'), ('LIBERADA', 'Liberada'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='GERADA', max_length=20)),
                ('chave_unica', models.CharField(max_length=160, unique=True)),
                ('referencia_pagamento', models.CharField(blank=True, max_length=80)),
                ('data_liberacao', models.DateTimeField(blank=True, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_gerais', to='orcamentos.itemorcamento')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_gerais', to='ordens.ordemservico')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_gerais', to='estoque.produto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_gerais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao', '-id'],
                'indexes': [models.Index(fields=['tecnico', 'status'], name='caixa_comis_tecnico_0fd117_idx'), models.Index(fields=['ordem_servico', 'status'], name='caixa_comis_ordem_s_206250_idx'), models.Index(fields=['tipo'], name='caixa_comis_tipo_4d717a_idx'), models.Index(fields=['evento_gerador'], name='caixa_comis_evento__ab37d9_idx')],
            },
        ),
    ]
