# Generated by Django 5.2.6 on 2026-03-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0017_comissao'),
        ('ordens', '0021_servicopeca_item_orcamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_gerais', to='ordens.ordemservico'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_gerais', to=settings.AUTH_USER_MODEL),
        ),
    ]
