# Generated by Codex on 2026-03-11

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("caixa", "0018_alter_comissao_ordem_servico_alter_comissao_tecnico"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="caixa",
            constraint=models.UniqueConstraint(fields=("data",), name="caixa_unico_por_data"),
        ),
        migrations.AddConstraint(
            model_name="caixa",
            constraint=models.UniqueConstraint(
                fields=("aberto",),
                condition=Q(aberto=True),
                name="caixa_apenas_um_aberto",
            ),
        ),
    ]
