# Generated by Codex on 2026-03-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caixa", "0019_caixa_regras_operacionais"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caixa",
            options={"ordering": ["-data", "-id"]},
        ),
    ]
