# Generated by Django 5.2.6 on 2026-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0020_alter_caixa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='tipo',
            field=models.CharField(choices=[('SERVICO', 'Servico'), ('PECA', 'Peca'), ('COMISSAO_VENDAS', 'Comissao sobre vendas'), ('BONUS_PRODUTO', 'Bonus por produto'), ('BONUS_RETIRADA', 'Bonus por retirada'), ('BONUS_SERVICO', 'Bonus de servico')], max_length=20),
        ),
    ]
