# Generated by Django 5.2.6 on 2026-03-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0021_alter_comissao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('receber', 'Contas a Receber')], default='receber', max_length=10),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='tipo',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('variavel', 'Variável')], default='variavel', max_length=20),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='tipo',
            field=models.CharField(choices=[('SERVICO', 'Serviço'), ('PECA', 'Peça'), ('COMISSAO_VENDAS', 'Comissão sobre vendas'), ('BONUS_PRODUTO', 'Bônus por produto'), ('BONUS_RETIRADA', 'Bônus por retirada'), ('BONUS_SERVICO', 'Bônus de serviço')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(choices=[('avista', 'À vista'), ('aprazo', 'A prazo')], default='avista', max_length=10),
        ),
        migrations.AlterField(
            model_name='lancamentocaixa',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número do talão ou comprovante', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regracomissaotecnico',
            name='momento_liberacao',
            field=models.CharField(choices=[('entregue_pago', 'Somente após entrega ao cliente + pagamento'), ('pronto_contactado', 'A partir de pronto contactado (adiantamento)')], default='entregue_pago', max_length=24),
        ),
        migrations.AlterField(
            model_name='regrapremiometa',
            name='publico',
            field=models.CharField(choices=[('tecnico', 'Técnicos'), ('atendente', 'Atendentes'), ('todos_operacionais', 'Todos operacionais')], default='tecnico', max_length=30),
        ),
    ]
