# Generated by Django 5.2.6 on 2026-03-18 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _backfill_competencia_fonte(apps, schema_editor):
    Comissao = apps.get_model("caixa", "Comissao")
    for comissao in Comissao.objects.all().iterator():
        update_fields = []
        if not comissao.competencia:
            data_ref = getattr(comissao, "data_criacao", None) or timezone.now()
            if hasattr(data_ref, "date"):
                data_ref = data_ref.date()
            comissao.competencia = data_ref.replace(day=1)
            update_fields.append("competencia")
        if not (comissao.fonte_referencia or "").strip():
            partes = str(comissao.chave_unica or "").split(":", 2)
            fonte = (partes[2] if len(partes) >= 3 else "").strip()
            if fonte:
                comissao.fonte_referencia = fonte
                update_fields.append("fonte_referencia")
        if update_fields:
            comissao.save(update_fields=update_fields)


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0022_alter_categoriafinanceira_tipo_and_more'),
        ('estoque', '0014_alter_produto_tipo_item'),
        ('orcamentos', '0004_alter_itemorcamento_tipo_item'),
        ('ordens', '0024_alter_linhatrabalho_tipo_evento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='competencia',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='comissao',
            name='fonte_referencia',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='ComissaoLotePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=48, unique=True)),
                ('competencia', models.DateField(db_index=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('criterio', models.CharField(choices=[('servicos_finalizados', 'Serviços finalizados'), ('retirado_pago', 'Retirado e pago')], default='servicos_finalizados', max_length=24)),
                ('percentual_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentual_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentual_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('incluir_servicos', models.BooleanField(default=True)),
                ('incluir_pecas', models.BooleanField(default=True)),
                ('incluir_vendas', models.BooleanField(default=False)),
                ('total_itens', models.PositiveIntegerField(default=0)),
                ('total_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=12)),
                ('observacao', models.CharField(blank=True, max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_comissao_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='comissao',
            name='lote_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes', to='caixa.comissaolotepagamento'),
        ),
        migrations.RunPython(_backfill_competencia_fonte, _noop_reverse),
        migrations.AddIndex(
            model_name='comissao',
            index=models.Index(fields=['fonte_referencia'], name='caixa_comis_fonte_r_5f2317_idx'),
        ),
        migrations.AddIndex(
            model_name='comissaolotepagamento',
            index=models.Index(fields=['competencia', 'status'], name='caixa_comis_compete_f4eb07_idx'),
        ),
    ]
