# Generated by Django 5.2.6 on 2026-03-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0023_comissao_competencia_comissao_fonte_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFixoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Informe o primeiro dia do mes de referencia.')),
                ('descricao', models.CharField(max_length=140)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_fixos_mensais', to='caixa.centrocusto')),
            ],
            options={
                'ordering': ['-competencia', 'descricao', '-id'],
                'indexes': [models.Index(fields=['competencia', 'status'], name='caixa_custo_compete_19cc46_idx')],
            },
        ),
    ]
