# Generated by Django 5.2.6 on 2026-04-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0025_pagamento_chave_idempotencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='caixa.categoriafinanceira'),
        ),
    ]
