# Generated by Django 5.2.6 on 2026-04-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0026_contapagar_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='custofixomensal',
            name='categoria_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_fixos_mensais', to='caixa.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='caixa.categoriafinanceira'),
        ),
    ]
