# Generated by Django 5.2.6 on 2026-04-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0027_custofixomensal_categoria_financeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='conferencia_formas_pagamento',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
