# Generated by Django 5.2.6 on 2026-04-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0028_caixa_conferencia_formas_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
