# Generated by Django 5.2.6 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0029_pagamento_desconto_pagamento_desconto_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(choices=[('avista', 'à vista'), ('aprazo', 'A prazo')], default='avista', max_length=10),
        ),
    ]
