# Generated by Django 5.2.6 on 2026-05-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0030_alter_formapagamento_tipo'),
        ('configuracoes', '0049_configuracaoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='configuracoes.empresa'),
        ),
    ]
