# Generated by Django 5.2.6 on 2026-07-10 16:09

from django.db import migrations, models


def consolidar_categorias_duplicadas(apps, schema_editor):
    Categoria = apps.get_model("caixa", "CategoriaFinanceira")
    referencias = (
        (apps.get_model("caixa", "ContaReceber"), "categoria_id"),
        (apps.get_model("caixa", "LancamentoCaixa"), "categoria_id"),
        (apps.get_model("caixa", "CustoFixoMensal"), "categoria_financeira_id"),
        (apps.get_model("caixa", "ContaPagar"), "categoria_id"),
    )

    chaves = Categoria.objects.values_list("nome", "tipo").distinct()
    for nome, tipo in chaves.iterator():
        categorias = list(Categoria.objects.filter(nome=nome, tipo=tipo).order_by("id"))
        if len(categorias) < 2:
            continue
        principal = categorias[0]
        duplicadas = categorias[1:]
        ids_duplicados = [categoria.id for categoria in duplicadas]
        if any(categoria.ativa for categoria in categorias) and not principal.ativa:
            principal.ativa = True
            principal.save(update_fields=["ativa"])
        for modelo, campo_id in referencias:
            modelo.objects.filter(**{f"{campo_id}__in": ids_duplicados}).update(**{campo_id: principal.id})
        Categoria.objects.filter(id__in=ids_duplicados).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0031_contapagar_empresa_contareceber_empresa'),
    ]

    operations = [
        migrations.RunPython(consolidar_categorias_duplicadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('nome', 'tipo'), name='caixa_categoria_financeira_nome_tipo_unico'),
        ),
    ]
