# Generated by Django 5.2.6 on 2026-07-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0034_pagamento_formas_pagamento_compostas'),
        ('configuracoes', '0069_fornecedorgarantia_municipio_fornecedorgarantia_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriagarantia',
            name='conta_receber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_garantia_vinculada', to='caixa.contareceber'),
        ),
        migrations.AddField(
            model_name='auditoriagarantia',
            name='data_base_cobranca',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriagarantia',
            name='prazo_pagamento_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditoriagarantia',
            name='valor_aprovado_fabricante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='auditoriagarantia',
            name='valor_recebido_fabricante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='auditoriagarantia',
            name='vencimento_previsto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='data_base_cobranca',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='fornecedor_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_garantia', to='configuracoes.fornecedorgarantia'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='marca_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_garantia', to='configuracoes.marcagarantia'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='prazo_pagamento_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='referencia_cobranca',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='regra_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_garantia', to='configuracoes.regragarantiamarca'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_aprovado_garantia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
