# Generated by Django 5.2.6 on 2026-08-02 20:44

import django.db.models.deletion
from django.db import migrations, models


def preencher_empresa_financeiro(apps, schema_editor):
    Empresa = apps.get_model("configuracoes", "Empresa")
    Caixa = apps.get_model("caixa", "Caixa")
    Pagamento = apps.get_model("caixa", "Pagamento")
    Lancamento = apps.get_model("caixa", "LancamentoCaixa")
    CustoFixo = apps.get_model("caixa", "CustoFixoMensal")
    empresa_unica = Empresa.objects.order_by("id").first() if Empresa.objects.count() == 1 else None

    for pagamento in Pagamento.objects.select_related("ordem_servico", "stock_item").iterator(chunk_size=500):
        empresa_id = (
            getattr(pagamento.stock_item, "empresa_id", None)
            or getattr(pagamento.ordem_servico, "empresa_id", None)
            or getattr(empresa_unica, "id", None)
        )
        if empresa_id:
            Pagamento.objects.filter(pk=pagamento.pk).update(empresa_id=empresa_id)

    for lancamento in Lancamento.objects.select_related("usuario").iterator(chunk_size=500):
        empresa_id = getattr(lancamento.usuario, "empresa_id", None) or getattr(empresa_unica, "id", None)
        if empresa_id:
            Lancamento.objects.filter(pk=lancamento.pk).update(empresa_id=empresa_id)

    if empresa_unica:
        Caixa.objects.filter(empresa__isnull=True).update(empresa=empresa_unica)
        CustoFixo.objects.filter(empresa__isnull=True).update(empresa=empresa_unica)
        Pagamento.objects.filter(empresa__isnull=True).update(empresa=empresa_unica)
        Lancamento.objects.filter(empresa__isnull=True).update(empresa=empresa_unica)


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0035_garantia_cobranca_por_marca'),
        ('configuracoes', '0076_user_perm_estoque_avaria_user_perm_estoque_cedencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='custofixomensal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custos_fixos_mensais', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_caixa', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='configuracoes.empresa'),
        ),
        migrations.RunPython(preencher_empresa_financeiro, migrations.RunPython.noop),
    ]
