# Generated by Django 5.2.6 on 2026-08-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0036_caixa_empresa_custofixomensal_empresa_and_more'),
        ('configuracoes', '0077_empresa_limite_cedencia_sem_aprovacao_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caixa',
            name='caixa_unico_por_data',
        ),
        migrations.RemoveConstraint(
            model_name='caixa',
            name='caixa_apenas_um_aberto',
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'data'), name='caixa_empresa_unico_por_data'),
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('data',), name='caixa_legado_unico_por_data'),
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(condition=models.Q(('aberto', True), ('empresa__isnull', False)), fields=('empresa',), name='caixa_empresa_apenas_um_aberto'),
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(condition=models.Q(('aberto', True), ('empresa__isnull', True)), fields=('aberto',), name='caixa_legado_apenas_um_aberto'),
        ),
    ]
