# Generated by Django 5.2.6 on 2026-08-03 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0037_remove_caixa_caixa_unico_por_data_and_more'),
        ('configuracoes', '0077_empresa_limite_cedencia_sem_aprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DREFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Primeiro dia do mes fechado.')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('receita_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receita_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receita_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cmv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lucro_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('perdas_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('despesas_operacionais', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('resultado_operacional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margem', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_dre', to='configuracoes.empresa')),
                ('fechado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_dre_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-competencia', '-fechado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'competencia'), name='dre_fechamento_empresa_competencia_unica'), models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('competencia',), name='dre_fechamento_legado_competencia_unica')],
            },
        ),
    ]
