# Generated by Django 5.2.6 on 2026-08-03 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0038_drefechamento'),
        ('configuracoes', '0077_empresa_limite_cedencia_sem_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesarecorrente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_recorrentes', to='configuracoes.empresa'),
        ),
    ]
