# Generated by Django 5.2.6 on 2026-08-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0040_backfill_empresa_despesa_recorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='drefechamento',
            name='impostos_estimados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='drefechamento',
            name='taxas_recebimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='aliquota_tributaria_estimada',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=7),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='encargos_gerenciais_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='impostos_estimados',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='taxas_recebimento_estimadas',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
