# Generated by Django 5.2.6 on 2026-08-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0042_backfill_encargos_gerenciais_pagamento'),
        ('configuracoes', '0078_fornecedorgarantia_empresa_marcagarantia_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoriafinanceira',
            name='caixa_categoria_financeira_nome_tipo_unico',
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='configuracoes.empresa'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome', 'tipo'), name='caixa_categoria_empresa_nome_tipo_unico'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome', 'tipo'), name='caixa_categoria_legado_nome_tipo_unico'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='caixa_centro_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='caixa_centro_legado_nome_unico'),
        ),
    ]
