# Generated by Django 5.2.6 on 2026-08-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0043_remove_categoriafinanceira_caixa_categoria_financeira_nome_tipo_unico_and_more'),
        ('configuracoes', '0080_parceiroexpedicao_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='configuracoes.empresa'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='codigo',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'nome'), name='caixa_forma_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'codigo'), name='caixa_forma_empresa_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('nome',), name='caixa_forma_legado_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('empresa__isnull', True)), fields=('codigo',), name='caixa_forma_legado_codigo_unico'),
        ),
    ]
