# Generated by Django 5.2.6 on 2026-08-06 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_conciliacoes_existentes(apps, schema_editor):
    Linha = apps.get_model('caixa', 'LinhaExtratoBancario')
    Conciliacao = apps.get_model('caixa', 'ConciliacaoBancaria')
    ConciliacaoLinha = apps.get_model('caixa', 'ConciliacaoBancariaLinha')
    ConciliacaoMovimento = apps.get_model('caixa', 'ConciliacaoBancariaMovimento')
    linhas = Linha.objects.filter(status__in=['conciliado', 'divergente'], movimento__isnull=False).select_related('movimento')
    for linha in linhas.iterator():
        movimento = linha.movimento
        total_movimentos = movimento.valor if movimento.tipo == 'entrada' else -movimento.valor
        conciliacao = Conciliacao.objects.create(
            empresa_id=linha.empresa_id,
            conta_id=linha.conta_id,
            status=linha.status,
            total_extrato=linha.valor,
            total_movimentos=total_movimentos,
            diferenca=linha.valor - total_movimentos,
            justificativa=linha.justificativa,
            conciliado_por_id=linha.conciliado_por_id,
        )
        if linha.conciliado_em:
            Conciliacao.objects.filter(pk=conciliacao.pk).update(conciliado_em=linha.conciliado_em)
        ConciliacaoLinha.objects.create(conciliacao_id=conciliacao.pk, linha_id=linha.pk)
        ConciliacaoMovimento.objects.create(conciliacao_id=conciliacao.pk, movimento_id=movimento.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0046_tesouraria_e_conciliacao'),
        ('configuracoes', '0088_fornecedor_comercial_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('conciliado', 'Conciliado'), ('divergente', 'Divergente justificado'), ('desfeito', 'Desfeito')], db_index=True, max_length=12)),
                ('total_extrato', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_movimentos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=14)),
                ('justificativa', models.TextField(blank=True)),
                ('conciliado_em', models.DateTimeField(auto_now_add=True)),
                ('desfeito_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_desfazimento', models.TextField(blank=True)),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_bancarias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='caixa.contabancaria')),
                ('desfeito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_bancarias_desfeitas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_bancarias', to='configuracoes.empresa')),
            ],
            options={
                'ordering': ['-conciliado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacaoBancariaLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_extrato', to='caixa.conciliacaobancaria')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_conciliacoes', to='caixa.linhaextratobancario')),
            ],
        ),
        migrations.CreateModel(
            name='ConciliacaoBancariaMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_movimento', to='caixa.conciliacaobancaria')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_conciliacoes', to='caixa.movimentobancario')),
            ],
        ),
        migrations.RunPython(migrar_conciliacoes_existentes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='conciliacaobancaria',
            index=models.Index(fields=['empresa', 'conta', 'status'], name='cx_conc_emp_cta_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='conciliacaobancarialinha',
            constraint=models.UniqueConstraint(fields=('conciliacao', 'linha'), name='conciliacao_linha_unica'),
        ),
        migrations.AddConstraint(
            model_name='conciliacaobancariamovimento',
            constraint=models.UniqueConstraint(fields=('conciliacao', 'movimento'), name='conciliacao_movimento_unico'),
        ),
    ]
