# Generated by Django 5.2.6 on 2026-08-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0047_conciliacaobancaria_conciliacaobancarialinha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentobancario',
            name='origem_tipo',
            field=models.CharField(choices=[('pagamento', 'Pagamento'), ('conta_pagar', 'Pagamento de conta a pagar'), ('transferencia', 'Transferência'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('pagamento', 'Pagamento'), ('conta_pagar', 'Pagamento de conta a pagar'), ('lancamento_caixa', 'Lançamento de caixa'), ('estorno', 'Estorno'), ('ajuste', 'Ajuste controlado')], max_length=30),
        ),
    ]
