# Generated by Django 5.2.6 on 2026-08-06 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0048_alter_movimentobancario_origem_tipo_and_more'),
        ('configuracoes', '0088_fornecedor_comercial_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacaobancaria',
            name='descricao_diferenca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conciliacaobancaria',
            name='movimento_diferenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_com_diferenca_lancada', to='caixa.movimentobancario'),
        ),
        migrations.AddField(
            model_name='conciliacaobancaria',
            name='tipo_diferenca',
            field=models.CharField(blank=True, choices=[('tarifa', 'Tarifa bancária'), ('juros', 'Juros'), ('rendimento', 'Rendimento'), ('ajuste', 'Outro ajuste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentocaixa',
            name='natureza',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('transferencia', 'Transferência de tesouraria'), ('capital', 'Capital e aportes')], db_index=True, default='operacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentobancario',
            name='origem_tipo',
            field=models.CharField(choices=[('pagamento', 'Pagamento'), ('conta_pagar', 'Pagamento de conta a pagar'), ('conciliacao_diferenca', 'Diferença de conciliação'), ('aporte_capital', 'Aporte de capital'), ('transferencia', 'Transferência'), ('manual', 'Manual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimentofinanceiro',
            name='natureza',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('transferencia', 'Transferência de tesouraria'), ('capital', 'Capital e aportes')], db_index=True, default='operacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('pagamento', 'Pagamento'), ('conta_pagar', 'Pagamento de conta a pagar'), ('conciliacao_diferenca', 'Diferença de conciliação'), ('aporte_capital', 'Capital ou aporte'), ('lancamento_caixa', 'Lançamento de caixa'), ('estorno', 'Estorno'), ('ajuste', 'Ajuste controlado')], max_length=30),
        ),
        migrations.CreateModel(
            name='AporteCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('capital_social', 'Capital social inicial/aumento de capital'), ('adiantamento_socio', 'Adiantamento para futuro aumento de capital'), ('emprestimo_socio', 'Empréstimo de sócio'), ('outro', 'Outra injeção de recursos')], max_length=24)),
                ('descricao', models.CharField(max_length=255)),
                ('aportante', models.CharField(blank=True, max_length=160)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_competencia', models.DateField(db_index=True)),
                ('data_movimento', models.DateField(db_index=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('chave_idempotencia', models.CharField(max_length=160, unique=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_capital', to='caixa.caixa')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes_capital', to='caixa.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes_capital', to='configuracoes.empresa')),
                ('lancamento_caixa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aporte_capital', to='caixa.lancamentocaixa')),
                ('movimento_bancario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aporte_capital', to='caixa.movimentobancario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_movimento', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='aporte_capital_valor_positivo')],
            },
        ),
    ]
