# Generated by Django 5.2.6 on 2026-08-11 23:18

import django.db.models.deletion
from django.db import migrations, models


def cancelar_recebiveis_zero(apps, schema_editor):
    ContaReceber = apps.get_model("caixa", "ContaReceber")
    ContaReceber.objects.filter(
        tipo_origem="cliente_os",
        valor_original=0,
        valor_aberto=0,
    ).update(status="cancelada")


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0049_conciliacaobancaria_descricao_diferenca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocaixa',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='caixa.contabancaria'),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_saida', to='caixa.formapagamento'),
        ),
        migrations.AlterField(
            model_name='lancamentocaixa',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='caixa.caixa'),
        ),
        migrations.AlterField(
            model_name='movimentobancario',
            name='origem_tipo',
            field=models.CharField(choices=[('pagamento', 'Pagamento'), ('conta_pagar', 'Pagamento de conta a pagar'), ('conciliacao_diferenca', 'Diferença de conciliação'), ('aporte_capital', 'Aporte de capital'), ('transferencia', 'Transferência'), ('lancamento_caixa', 'Lançamento financeiro'), ('manual', 'Manual')], max_length=30),
        ),
        migrations.RunPython(cancelar_recebiveis_zero, migrations.RunPython.noop),
    ]
