# Generated by Django 5.2.6 on 2026-08-12 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preencher_datas_e_empresa_historicas(apps, schema_editor):
    ContaPagar = apps.get_model("caixa", "ContaPagar")
    PagamentoContaPagar = apps.get_model("caixa", "PagamentoContaPagar")

    for conta in ContaPagar.objects.all().iterator():
        data_base = conta.criado_em.date() if conta.criado_em else conta.vencimento
        ContaPagar.objects.filter(pk=conta.pk).update(
            data_emissao=data_base,
            data_competencia=data_base,
            chave_idempotencia=f"conta-pagar-legado:{conta.pk}",
        )

    for pagamento in PagamentoContaPagar.objects.select_related(
        "conta", "forma_pagamento", "caixa"
    ).iterator():
        data_base = pagamento.data.date() if pagamento.data else pagamento.conta.data_competencia
        conta_bancaria_id = None
        if not pagamento.caixa_id and pagamento.forma_pagamento_id:
            conta_bancaria_id = pagamento.forma_pagamento.conta_bancaria_liquidacao_id
        PagamentoContaPagar.objects.filter(pk=pagamento.pk).update(
            empresa_id=pagamento.conta.empresa_id,
            conta_bancaria_id=conta_bancaria_id,
            data_competencia=pagamento.conta.data_competencia,
            data_movimento=getattr(pagamento.caixa, "data", None) or data_base,
            chave_idempotencia=f"pagamento-conta-pagar-legado:{pagamento.pk}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0050_lancamentocaixa_conta_bancaria_and_more'),
        ('configuracoes', '0089_configuracaosistema_pdf_relatorio_modo_resumido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentocontapagar',
            options={'ordering': ['-data_movimento', '-data', '-id']},
        ),
        migrations.AddField(
            model_name='contapagar',
            name='chave_idempotencia',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='caixa/contas_pagar/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='data_competencia',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='data_emissao',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='pagamento_conta_pagar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamento_caixa', to='caixa.pagamentocontapagar'),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='chave_idempotencia',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='caixa/pagamentos_fornecedores/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_conta_pagar', to='caixa.contabancaria'),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='data_competencia',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='data_movimento',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_contas_pagar', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='estornado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='estornado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_contas_pagar_estornados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='motivo_estorno',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('estornado', 'Estornado')], db_index=True, default='confirmado', max_length=12),
        ),
        migrations.RunPython(preencher_datas_e_empresa_historicas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pagamentocontapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pagamento_conta_pagar_valor_positivo'),
        ),
    ]
