# Generated by Django 5.2.6 on 2026-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0051_alter_pagamentocontapagar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='natureza_economica',
            field=models.CharField(choices=[('despesa_operacional', 'Despesa operacional'), ('estoque', 'Compra para estoque (ativo)'), ('imobilizado', 'Investimento / imobilizado'), ('tributo', 'Tributo ou imposto'), ('financeira', 'Despesa financeira'), ('outra_nao_operacional', 'Outra natureza não operacional')], db_index=True, default='despesa_operacional', max_length=24),
        ),
    ]
