# Generated by Django 5.2.6 on 2026-08-12 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0052_contapagar_natureza_economica'),
        ('configuracoes', '0090_user_perm_caixa_conciliar_banco_and_more'),
        ('ordens', '0047_pedidocompra_conta_pagar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('emissor', models.CharField(max_length=100)),
                ('final', models.CharField(max_length=4)),
                ('responsavel', models.CharField(blank=True, max_length=160)),
                ('limite', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dia_fechamento', models.PositiveSmallIntegerField(default=20)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=28)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_pagamento_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_corporativos', to='caixa.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_corporativos', to='configuracoes.empresa')),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompraCartaoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(db_index=True)),
                ('data_competencia', models.DateField(db_index=True)),
                ('fornecedor', models.CharField(max_length=160)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='caixa/cartoes/compras/%Y/%m/')),
                ('chave_idempotencia', models.CharField(max_length=160, unique=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('estornada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_estorno', models.TextField(blank=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='caixa.cartaocorporativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='caixa.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='caixa.centrocusto')),
                ('custo_os', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_cartao', to='ordens.custoordemservico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao_corporativo', to='configuracoes.empresa')),
                ('estornada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cartao_estornadas', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='ordens.ordemservico')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartaoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True, help_text='Use o primeiro dia do mês da fatura.')),
                ('data_fechamento', models.DateField()),
                ('vencimento', models.DateField(db_index=True)),
                ('total_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('parcial', 'Paga parcialmente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=12)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='caixa.cartaocorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas_cartoes', to='configuracoes.empresa')),
            ],
            options={
                'ordering': ['-competencia', 'cartao__nome'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('saldo_sistema', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_extrato', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('fechado', 'Fechado'), ('reaberto', 'Reaberto')], db_index=True, default='fechado', max_length=10)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('reaberto_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_reabertura', models.TextField(blank=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos', to='caixa.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_bancarios', to='configuracoes.empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_bancarios', to=settings.AUTH_USER_MODEL)),
                ('reaberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_bancarios_reabertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo_fim', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('hash_arquivo', models.CharField(max_length=64)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('saldo_inicial_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('saldo_final_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantidade_linhas', models.PositiveIntegerField(default=0)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato', to='caixa.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato', to='configuracoes.empresa')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='linhaextratobancario',
            name='importacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='caixa.importacaoextratobancario'),
        ),
        migrations.CreateModel(
            name='MovimentoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('devolucao_afac', 'Devolução de AFAC'), ('amortizacao_emprestimo', 'Amortização de empréstimo de sócio'), ('retirada_capital', 'Retirada / redução de capital'), ('juros_emprestimo', 'Juros de empréstimo de sócio')], max_length=28)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_competencia', models.DateField(db_index=True)),
                ('data_movimento', models.DateField(db_index=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='caixa/socios/%Y/%m/')),
                ('chave_idempotencia', models.CharField(max_length=160, unique=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('aporte_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_saida', to='caixa.aportecapital')),
                ('aprovado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_socios_aprovados', to=settings.AUTH_USER_MODEL)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_socios', to='caixa.caixa')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_socios', to='caixa.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_socios', to='configuracoes.empresa')),
                ('lancamento_caixa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimento_socio', to='caixa.lancamentocaixa')),
                ('movimento_bancario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimento_socio', to='caixa.movimentobancario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_socios_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_movimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoFaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='caixa/cartoes/pagamentos/%Y/%m/')),
                ('chave_idempotencia', models.CharField(max_length=160, unique=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_faturas_cartao', to='caixa.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_faturas_cartao', to='configuracoes.empresa')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='caixa.faturacartaocorporativo')),
                ('movimento_bancario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_fatura_cartao', to='caixa.movimentobancario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_movimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaCartaoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('vencimento', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estornada_em', models.DateTimeField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='caixa.compracartaocorporativo')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='caixa.faturacartaocorporativo')),
            ],
            options={
                'ordering': ['vencimento', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='cartaocorporativo',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome', 'final'), name='cartao_corp_empresa_nome_final_unico'),
        ),
        migrations.AddConstraint(
            model_name='compracartaocorporativo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='compra_cartao_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='compracartaocorporativo',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_parcelas__gt', 0)), name='compra_cartao_parcelas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='faturacartaocorporativo',
            constraint=models.UniqueConstraint(fields=('cartao', 'competencia'), name='fatura_cartao_competencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='fechamentobancario',
            constraint=models.UniqueConstraint(fields=('conta', 'periodo_inicio', 'periodo_fim'), name='fechamento_banco_periodo_unico'),
        ),
        migrations.AddConstraint(
            model_name='importacaoextratobancario',
            constraint=models.UniqueConstraint(fields=('conta', 'hash_arquivo'), name='extrato_conta_hash_unico'),
        ),
        migrations.AddConstraint(
            model_name='movimentosocio',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='movimento_socio_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagamentofaturacartao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pagamento_fatura_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelacartaocorporativo',
            constraint=models.UniqueConstraint(fields=('compra', 'numero'), name='parcela_cartao_numero_unico'),
        ),
    ]
