# Generated by Django 5.2.6 on 2026-08-12 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0053_cartaocorporativo_compracartaocorporativo_and_more'),
        ('configuracoes', '0091_user_perm_caixa_administrar_plano_contas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('ativo', 'Ativo'), ('passivo', 'Passivo'), ('patrimonio', 'Patrimônio líquido'), ('receita', 'Receita'), ('despesa', 'Despesa')], max_length=12)),
                ('aceita_lancamento', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PlanoContasVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=180)),
                ('ativo', models.BooleanField(db_index=True, default=False)),
                ('validado_contador', models.BooleanField(default=False)),
                ('observacao_validacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_contas_versoes', to='configuracoes.empresa')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MapeamentoEventoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos_credito', to='caixa.contacontabil')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos_debito', to='caixa.contacontabil')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos', to='caixa.planocontasversao')),
            ],
        ),
        migrations.CreateModel(
            name='LoteContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True)),
                ('evento', models.CharField(max_length=50)),
                ('origem_tipo', models.CharField(max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=120)),
                ('historico', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('contabilizado', 'Contabilizado'), ('estornado', 'Estornado')], db_index=True, default='contabilizado', max_length=14)),
                ('chave_idempotencia', models.CharField(max_length=180, unique=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_contabeis', to='configuracoes.empresa')),
                ('estorno_de', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lote_estorno', to='caixa.lotecontabil')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_contabeis_registrados', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='caixa.planocontasversao')),
            ],
            options={
                'ordering': ['-competencia', '-id'],
            },
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='caixa.planocontasversao'),
        ),
        migrations.CreateModel(
            name='PartidaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas_contabeis', to='caixa.centrocusto')),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_credito', to='caixa.contacontabil')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_debito', to='caixa.contacontabil')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='caixa.lotecontabil')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='partida_contabil_valor_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='planocontasversao',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='plano_contas_empresa_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='mapeamentoeventocontabil',
            constraint=models.UniqueConstraint(fields=('plano', 'evento'), name='mapeamento_contabil_evento_unico'),
        ),
        migrations.AddConstraint(
            model_name='contacontabil',
            constraint=models.UniqueConstraint(fields=('plano', 'codigo'), name='conta_contabil_plano_codigo_unico'),
        ),
    ]
