# Generated by Django 5.2.6 on 2026-08-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0054_contacontabil_planocontasversao_and_more'),
        ('configuracoes', '0091_user_perm_caixa_administrar_plano_contas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='configuracoes.fornecedorgarantia'),
        ),
    ]
