# Generated by Django 5.2.6 on 2026-08-12 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0055_contapagar_fornecedor_cadastro'),
        ('configuracoes', '0092_user_perm_caixa_corrigir_lancamentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoLancamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_anteriores', models.JSONField(default=dict)),
                ('dados_corrigidos', models.JSONField(default=dict)),
                ('motivo', models.TextField()),
                ('corrigido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-corrigido_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='corrigido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcoes_lancamentos_caixa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcoes_lancamentos_caixa', to='configuracoes.empresa'),
        ),
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcoes_auditadas', to='caixa.lancamentocaixa'),
        ),
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='movimento_bancario_corrigido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes_como_movimento_novo', to='caixa.movimentobancario'),
        ),
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='movimento_bancario_estorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes_como_estorno', to='caixa.movimentobancario'),
        ),
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='movimento_financeiro_corrigido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes_como_movimento_novo', to='caixa.movimentofinanceiro'),
        ),
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='movimento_financeiro_estorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes_como_estorno', to='caixa.movimentofinanceiro'),
        ),
    ]
