# Generated by Django 5.2.6 on 2026-08-12 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0056_correcaolancamentocaixa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correcaolancamentocaixa',
            name='tipo',
            field=models.CharField(choices=[('edicao', 'Edição'), ('cancelamento', 'Cancelamento')], db_index=True, default='edicao', max_length=15),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_caixa_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=12),
        ),
        migrations.AddField(
            model_name='movimentobancario',
            name='motivo_neutralizacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimentobancario',
            name='neutralizacao_de',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimento_neutralizador', to='caixa.movimentobancario'),
        ),
        migrations.AddField(
            model_name='movimentobancario',
            name='neutralizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentobancario',
            name='neutralizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_bancarios_neutralizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentobancario',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('neutralizado', 'Neutralizado por contrapartida')], db_index=True, default='ativo', max_length=14),
        ),
    ]
