# Generated by Django 5.2.6 on 2026-01-19 10:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_cliente',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Número do Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter de 11 a 14 dígitos (com ou sem formatação).', regex='^\\d{11,14}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 9 a 15 dígitos. Formato: +5511999999999', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
