# Generated by Django 5.2.6 on 2026-01-19 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_data_cadastro_cliente_numero_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='O CNPJ deve conter exatamente 14 dígitos numéricos.', regex='^\\d{14}$')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo / Razão Social'),
        ),
    ]
