# Generated by Django 5.2.6 on 2026-01-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cnpj_alter_cliente_cpf_alter_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
