# Generated by Django 5.2.6 on 2026-01-30 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_bairro_cliente_cidade_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_cpf_e6905f_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_cnpj_db43af_idx',
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O documento deve conter 11 dígitos (CPF) ou 14 dígitos (CNPJ).', regex='^\\d{11}$|^\\d{14}$')], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ (legado)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF (legado)'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['documento'], name='clientes_cl_documen_76f212_idx'),
        ),
    ]
