# Generated by Django 5.2.6 on 2026-02-06 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_cliente_clientes_cl_cpf_e6905f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos. Formato: 11999999999', regex='^\\d{10,11}$')]),
        ),
    ]
