# Generated by Django 5.2.6 on 2026-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='origem_cliente',
            field=models.CharField(blank=True, choices=[('nao_informado', 'Não informado'), ('indicacao', 'Indicação'), ('google', 'Google'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('olx', 'OLX'), ('balcao', 'Balcão'), ('parceiro', 'Parceiro'), ('retorno', 'Retorno'), ('outros', 'Outros')], default='nao_informado', max_length=20, verbose_name='Origem do cliente'),
        ),
    ]
