# Generated by Django 5.2.6 on 2026-05-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_origem_cliente'),
        ('configuracoes', '0049_configuracaoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='configuracoes.empresa'),
        ),
    ]
