# Generated by Django 5.2.6 on 2026-07-10 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O documento deve conter 11 dígitos (CPF) ou 14 dígitos (CNPJ).', regex='^\\d{11}$|^[A-Z0-9]{14}$')], verbose_name='CPF/CNPJ'),
        ),
    ]
