# Generated by Django 5.2.6 on 2026-02-21 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo_usuario': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
