# Generated by Django 5.2.6 on 2026-03-04 20:26

from django.db import migrations, models


def preencher_tipo_item(apps, schema_editor):
    ItemOrcamento = apps.get_model("orcamentos", "ItemOrcamento")
    ItemOrcamento.objects.filter(origem="estoque").update(tipo_item="peca")
    ItemOrcamento.objects.filter(origem="manual").update(tipo_item="servico")


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_itemorcamento_tecnico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='tipo_item',
            field=models.CharField(choices=[('servico', 'Servico'), ('peca', 'Peca')], default='servico', max_length=20),
        ),
        migrations.RunPython(preencher_tipo_item, migrations.RunPython.noop),
    ]
