# Generated by Django 5.2.6 on 2026-03-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_itemorcamento_tipo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='tipo_item',
            field=models.CharField(choices=[('servico', 'Serviço'), ('peca', 'Peça')], default='servico', max_length=20),
        ),
    ]
