# Generated by Django 5.2.6 on 2026-04-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_alter_itemorcamento_tipo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='comissionavel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='desconto_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
