# Generated by Django 5.2.6 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0005_itemorcamento_comissionavel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemorcamento",
            name="desconto_percentual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="desconto_valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]

