# Generated by Django 5.2.6 on 2026-08-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_alter_itemorcamento_tecnico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='custo_estimado_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='fornecedor_estimado',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='referencia_cotacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='situacao_aquisicao',
            field=models.CharField(choices=[('nao_necessario', 'Não necessário'), ('a_comprar', 'A comprar'), ('solicitado', 'Solicitado'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='nao_necessario', max_length=20),
        ),
    ]
